In [1]:
from sklearn.datasets import load_files
import pandas as pd

In [2]:
#Malayalam
Mal_train=pd.read_csv("kannada_sentiment_full_train.tsv", sep='\t')


Mal_Dev=pd.read_csv("kannada_sentiment_full_dev.tsv", sep='\t')


Mal_test=pd.read_csv("kannada_sentiment_full_test_withoutlabels.tsv", sep='\t')

In [3]:
Mal_train

text        category
0     ಒಂದು ದೇಶದ ಮುಂದುವರಿಯುವುದು ಅದರ ಆರ್ಥಿಕ ಸ್ಥಿತಿಯನ್ನ...        Negative
1     ಕನ್ನಡದಲ್ಲಿ ಡೈಲಿ ಟೆಕ್ ಅಪ್ಡೇಟ್ಸ್ ಪಡೆಯಲು ಸಬ್ಸ್ಕ್ರ...        Positive
2                                        Super sar song     not-Kannada
3     Tiktokers present situation... nನೋಡುವವರು ಯಾರು ...        Negative
4                             Super ಸಾಂಗ್ ವೆರಿ ನೈಸ್....        Positive
...                                                 ...             ...
6207  @A.R.W   tumbad tanhaji andhadhun aise bahot h...     not-Kannada
6208                  പൊളി ഡാൻസ്🥰 രക്ഷിത് ഷെട്ടി മാസ്സ്     not-Kannada
6209  Bro...nNeen este Roast madudru...China ne beku...        Negative
6210  ಕೌಶಲ್ಯ ಇದ್ದವರ ಸಂಖ್ಯೆ ಕಡಿಮೆ ಇಲ್ಲ ಸರ್ ತುಂಬಾ ಪ್ರತ...        Positive
6211                                         26 M Views  Mixed feelings

[6212 rows x 2 columns]

In [4]:
Mal_train[0:5], Mal_Dev[0:5]

(                                                text     category
 0  ಒಂದು ದೇಶದ ಮುಂದುವರಿಯುವುದು ಅದರ ಆರ್ಥಿಕ ಸ್ಥಿತಿಯನ್ನ...     Negative
 1  ಕನ್ನಡದಲ್ಲಿ ಡೈಲಿ ಟೆಕ್ ಅಪ್ಡೇಟ್ಸ್ ಪಡೆಯಲು ಸಬ್ಸ್ಕ್ರ...     Positive
 2                                     Super sar song  not-Kannada
 3  Tiktokers present situation... nನೋಡುವವರು ಯಾರು ...     Negative
 4                          Super ಸಾಂಗ್ ವೆರಿ ನೈಸ್....     Positive,
                                                 text        category
 0  Binduge saryagi ugithidira good go ahead  we a...  Mixed feelings
 1                             yen song guru ...super        Positive
 2                                   my fevorat story     not-Kannada
 3                                  Super ತೋಗರಿ ತೀಪ್ಪ        Positive
 4  ನಿಮ್ಮ ಮಾತುಗಳು ಅಕ್ಷರಶಃ ಸತ್ಯ... ನಿಮ್ಮ ಈ ಸಾಮಾನ್ಯ ...        Positive)

In [5]:
#from ml2en import ml2en

In [6]:
#converter = ml2en()

#desti_lang={
#     'malayalam' : 'ml'
#}

In [7]:
#for key,value in desti_lang.items():
     #print(transt.translate(Mal_train['text']))
     #   Mal_train['text1']=Mal_train['text'].apply(lambda x: converter.transliterate(x))
     #   Mal_Dev['text1']=Mal_Dev['text'].apply(lambda x: converter.transliterate(x))
     #   Mal_test['text1']=Mal_test['text'].apply(lambda x: converter.transliterate(x))

In [8]:
Mal_train[61:70]

text     category
61                               SupernTelugu lo kuda     Positive
62                          Rakshit shetty sir ge jai     Positive
63                   different but unique & epic song  not-Kannada
64                        Even I had Same feelings..!  not-Kannada
65  First time movie nodoru taleli uoohe screenply...     Positive
66                         Super................ Song  not-Kannada
67                           Good job..  Goahead mahn  not-Kannada
68  En song guruve I love this song K G F bitre ed...     Positive
69  Nimage aa devaru olledu madali Appaji...nNimma...     Positive

In [9]:
Mal_Dev.head()

text        category
0  Binduge saryagi ugithidira good go ahead  we a...  Mixed feelings
1                             yen song guru ...super        Positive
2                                   my fevorat story     not-Kannada
3                                  Super ತೋಗರಿ ತೀಪ್ಪ        Positive
4  ನಿಮ್ಮ ಮಾತುಗಳು ಅಕ್ಷರಶಃ ಸತ್ಯ... ನಿಮ್ಮ ಈ ಸಾಮಾನ್ಯ ...        Positive

In [10]:
Mal_test.head()

id                                               text
0  Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1  Kan_2                                         Jai D Boss
2  Kan_3                                     Signature move
3  Kan_4                                     Super song bro
4  Kan_5                        Wow  Super agi helidira sir

In [11]:
# Train
Mal_train['category'].value_counts()

Positive          2823
Negative          1188
not-Kannada        916
unknown state      711
Mixed feelings     574
Name: category, dtype: int64

In [12]:
# Development 
Mal_Dev['category'].value_counts()

Positive          321
Negative          139
not-Kannada       110
unknown state      69
Mixed feelings     52
Name: category, dtype: int64

In [13]:
msg=Mal_train['text']

msgDev=Mal_Dev['text']

msgTest=Mal_test['text']

In [14]:
msgDev[50:70]

50    Guru ninge like beku andre kelu Kodthare adu b...
51                      super comedy drama togari tippa
52                                    @Deekshit Chandra
53    Enadru public help ago Vishayada bagge Mathadi...
54                        Nammantavrge spoorti nivu sir
55             Estu kelidru matte matte kelbeku ansutte
56                           Pakka 100 days movie  edu.
57                              Nice story togari tippa
58         ಶಂಕರ್ ಅಶ್ವಥ್ ರೊಂದಿಗೆ ಅತ್ಯಂತ ಸುಂದರವಾದ ಸಂದರ್ಶನ
59                                    Plz make in Hindi
60                                      Sooperb concept
61             Navu kuri Alla guru kaliyugada kaligallu
62                      Ye movie hindi mein hogi k nahi
63         Please innodh video maadi bro ticktock bagge
64       Nodarappa yaro heludrala ban yak madbeku antha
65                           super.nTogari Tippa Comody
66                ಏ... ಭೈ ಏನೋಪ ನೀ ಹಿಂಗ ಮೈ ತೊಳೆದು ಬಿಟ್ಟಿ
67    Kolthogiro kobri mitai mukadavle na..?nYap

In [15]:
#Remove Emojis

def emoji(msg): 
    
    msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
    
    msg_digit=msg_emoj.str.replace(r'[0-9]', ' ')

    msg_Spac = msg_digit.str.replace(r'_',' ')

    msg_Spac = msg_Spac.str.replace(r'.','')

    msg_Spac = msg_Spac.str.replace(r'!','')

    msg_Spac = msg_Spac.str.replace(r'#','')

    msg_Spac = msg_Spac.str.replace(r'%','')

    msg_Spac = msg_Spac.str.replace(r'&','')

    msg_Spac = msg_Spac.str.replace(r'’','')

    msg_Spac = msg_Spac.str.replace(r'(','')

    msg_Spac = msg_Spac.str.replace(r')','')

    msg_Spac = msg_Spac.str.replace(r'-','')

    msg_Spac = msg_Spac.str.replace(r'/','')

    msg_Spac = msg_Spac.str.replace(r':','')

    msg_Spac = msg_Spac.str.replace(r';','')

    msg_Spac = msg_Spac.str.replace(r'<','')

    msg_Spac = msg_Spac.str.replace(r'=','')

    msg_Spac = msg_Spac.str.replace(r'>','')

    msg_Spac = msg_Spac.str.replace(r'?','')

    msg_Spac = msg_Spac.str.replace(r'@','')

    msg_Spac = msg_Spac.str.replace(r'[','')

    msg_Spac = msg_Spac.str.replace(r']','')

    msg_Spac = msg_Spac.str.replace(r'^','')

    msg_Spac = msg_Spac.str.replace(r'{','')

    msg_Spac = msg_Spac.str.replace(r'}','')

    msg_Spac = msg_Spac.str.replace(r'|','')

    msg_Spac = msg_Spac.str.replace(r'~','')

    msg_Spac = msg_Spac.str.replace(r'+','')

    msg_Spac = msg_Spac.str.replace(r'\s+', ' ')


    return msg_Spac
    

In [16]:
msg_Train=emoji(msg)

msg_Dev=emoji(msgDev)

msg_Test=emoji(msgTest)

e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: The default value of regex will c

In [17]:
msg_Train[78:90], msg_Dev[50:70], #msg_Test[21:22]


(78                                           Hi Chi ugh
 79                nivu helidu sari nanu follow madthini
 80    Sir paisacom adara bagge video madi Open madod...
 81    Entha song na dislike madtiralla loafer nan ma...
 82                           Pubg kooda ban agbeku guru
 83                                  Manju Sonu ಅಭಿನಂದನೆ
 84                             That making was osm ASN 
 85                   ಈ ಹಾಡು ರಶ್ಮಿಕ ಮಂಗಣ್ಣನವರಿಗೆ ಅರ್ಪಣೆ 
 86                             Super guru awesome video
 87    Nandi Parthasarathi ಓಹೋ ನಂದಿನಿ ನಿಂದು ಮಿಲ್ಕ್ ಪಾ...
 88           prithvi nayak Roberrt bangada goth aagutte
 89                                One like for hands up
 Name: text, dtype: object,
 50    Guru ninge like beku andre kelu Kodthare adu b...
 51                      super comedy drama togari tippa
 52                                     Deekshit Chandra
 53    Enadru public help ago Vishayada bagge Mathadi...
 54                        Nammantavrge spoorti nivu sir
 55

In [18]:
Train_Df=pd.DataFrame(msg_Train)
Train_Df.columns=['Msg_with_Stopwords']

Dev_Df=pd.DataFrame(msg_Dev)
Dev_Df.columns=['Msg_with_Stopwords']

Test_Df=pd.DataFrame(msg_Test)
Test_Df.columns=['Msg_with_Stopwords']

In [19]:
Train_Df.shape, Dev_Df.shape, Test_Df.shape

((6212, 1), (691, 1), (768, 1))

In [20]:
# Removing Null Values

Train_Df['Msg_with_Stopwords']=Train_Df['Msg_with_Stopwords'].fillna("")

Dev_Df['Msg_with_Stopwords']=Dev_Df['Msg_with_Stopwords'].fillna("")

Test_Df['Msg_with_Stopwords']=Test_Df['Msg_with_Stopwords'].fillna("")


In [21]:
Mal_train.shape, Mal_Dev.shape,Train_Df.shape, Dev_Df.shape, Test_Df.shape

((6212, 2), (691, 2), (6212, 1), (691, 1), (768, 1))

In [22]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Joshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
stop_words = set(stopwords.words('english'))

In [24]:
Train_Df['Msg_without_Stopwords']=Train_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Dev_Df['Msg_without_Stopwords']=Dev_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Test_Df['Msg_without_Stopwords']=Test_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [25]:
Train_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_with_Stopwords'].tolist()]
Train_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_without_Stopwords'].tolist()]

Dev_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_with_Stopwords'].tolist()]
Dev_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_without_Stopwords'].tolist()]

Test_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_with_Stopwords'].tolist()]
Test_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_without_Stopwords'].tolist()]

In [26]:
Train_Data=pd.concat([Mal_train, Train_Df], axis=1)

Dev_Data=pd.concat([Mal_Dev, Dev_Df], axis=1)

Test_Data=pd.concat([Mal_test, Test_Df], axis=1)

In [27]:
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((6212, 6), (691, 6), (768, 6))

In [28]:
Train_Data=Train_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Dev_Data=Dev_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Test_Data=Test_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)


In [29]:
# Dataset Train & Dev are : (1) Message_Without_Stopwords and (2) labels
# Only Test is : (1) Message_Without_Stopwords
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((6212, 2), (691, 2), (768, 2))

In [30]:
Train_Data[78:90]

category                              Msg_without_Stopwords
78  unknown state                                         Hi Chi ugh
79       Positive              nivu helidu sari nanu follow madthini
80       Positive  Sir paisacom adara bagge video madi Open madod...
81       Negative  Entha song na dislike madtiralla loafer nan ma...
82  unknown state                         Pubg kooda ban agbeku guru
83  unknown state                                Manju Sonu ಅಭಿನಂದನೆ
84       Positive                                That making osm ASN
85       Negative                  ಈ ಹಾಡು ರಶ್ಮಿಕ ಮಂಗಣ್ಣನವರಿಗೆ ಅರ್ಪಣೆ
86       Positive                           Super guru awesome video
87       Negative  Nandi Parthasarathi ಓಹೋ ನಂದಿನಿ ನಿಂದು ಮಿಲ್ಕ್ ಪಾ...
88       Negative         prithvi nayak Roberrt bangada goth aagutte
89    not-Kannada                                     One like hands

In [31]:
Dev_Data

category                              Msg_without_Stopwords
0    Mixed feelings  Binduge saryagi ugithidira good go ahead enjoy...
1          Positive                                yen song guru super
2       not-Kannada                                      fevorat story
3          Positive                                  Super ತೋಗರಿ ತೀಪ್ಪ
4          Positive  ನಿಮ್ಮ ಮಾತುಗಳು ಅಕ್ಷರಶಃ ಸತ್ಯ ನಿಮ್ಮ ಈ ಸಾಮಾನ್ಯ ಜೀವ...
..              ...                                                ...
686        Negative   Nandi Parthasarathi ನಿಮ್ಮ ಅಪ್ಪ ದೊಡ್ ಗಾಂಡು ಸೂಳೆಮಗ
687        Negative                               Hugi guru badethawke
688        Positive                                       Trending wow
689        Positive  Troll Stupid Fans naanu adikke kano helthirodu...
690        Positive  JustAn Opinion ninu Tika mucchuEvattu Kannada ...

[691 rows x 2 columns]

In [32]:
Test_Data

id                              Msg_without_Stopwords
0      Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1      Kan_2                                         Jai D Boss
2      Kan_3                                     Signature move
3      Kan_4                                     Super song bro
4      Kan_5                         Wow Super agi helidira sir
..       ...                                                ...
763  Kan_764                                Thu thukali trailer
764  Kan_765  Siri gannadam galge haakbitallapa Thu yaro nin...
765  Kan_766  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...
766  Kan_767  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲnದಯವಿಟ...
767  Kan_768  magaluru kade kalsi avanannu navu avanige madd...

[768 rows x 2 columns]

In [33]:
import tensorflow as tf
tf.version.VERSION

'2.0.0-rc1'

In [1]:

import keras

Using TensorFlow backend.


In [35]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [36]:
x_train=Train_Data.Msg_without_Stopwords
x_dev=Dev_Data.Msg_without_Stopwords
x_test=Test_Data.Msg_without_Stopwords

In [37]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 


from keras.utils import to_categorical
y_train=Train_Data['Nlabel']
y_dev=Dev_Data['Nlabel']

y_train1 = to_categorical(y_train)
y_dev1 = to_categorical(y_dev)

In [38]:
y_train.shape
from keras.preprocessing.text import Tokenizer
num_labels = 5
vocab_size = 5000
batch_size = 100
num_epochs = 10

In [39]:
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(x_train)

In [40]:
X_train1 = tokenizer.texts_to_matrix(x_train)

X_dev1 = tokenizer.texts_to_matrix(x_dev)

X_test1=tokenizer.texts_to_matrix(x_test)

In [41]:
X_train1.shape, X_dev1.shape, y_train1.shape, y_dev1.shape

((6212, 5000), (691, 5000), (6212, 5), (691, 5))

In [42]:
type(X_train1), type(y_train1), type(X_dev1), type(y_dev1)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [43]:
import tensorflow as tf
from tensorflow import keras

# Basic Mode / ANN F1 score = 0.61

In [44]:
#let us build a basic model
model = keras.Sequential([
    keras.layers.Dense(512, input_shape=(vocab_size,)),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(512),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(num_labels),
    keras.layers.Activation('softmax')
])

model.summary()a

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               2560512   
_________________________________________________________________
activation (Activation)      (None, 512)               0         
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 2

In [45]:
num_epochs =10
batch_size = 128
history = model.fit(X_train1, y_train1, batch_size=batch_size, epochs=num_epochs,verbose=2)

Train on 6212 samples
Epoch 1/10
6212/6212 - 5s - loss: 1.3014 - accuracy: 0.4791
Epoch 2/10
6212/6212 - 2s - loss: 0.8938 - accuracy: 0.6492
Epoch 3/10
6212/6212 - 2s - loss: 0.6130 - accuracy: 0.7791
Epoch 4/10
6212/6212 - 2s - loss: 0.3948 - accuracy: 0.8662
Epoch 5/10
6212/6212 - 2s - loss: 0.2835 - accuracy: 0.8952
Epoch 6/10
6212/6212 - 2s - loss: 0.2319 - accuracy: 0.9156
Epoch 7/10
6212/6212 - 2s - loss: 0.1970 - accuracy: 0.9293
Epoch 8/10
6212/6212 - 2s - loss: 0.1813 - accuracy: 0.9322
Epoch 9/10
6212/6212 - 2s - loss: 0.1690 - accuracy: 0.9366
Epoch 10/10
6212/6212 - 2s - loss: 0.1630 - accuracy: 0.9406


In [46]:
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score

In [47]:
def predict(X_dev1,y_dev1,X_test1):
    loss, accuracy = model.evaluate(X_dev1,y_dev1,verbose=0)
    print('Accuracy: %f' % (accuracy*100))
    print('Loss: %f' % (loss*100))
    y_pred=model.predict_classes(X_dev1)

    # predict 
    predictions = model.predict(X_dev1, batch_size = 32)
    pred = np.argmax(predictions, axis=1)
    # label
    y_dev1 = np.argmax(y_dev1, axis=1)
    
    print(classification_report(y_dev1, pred))
    
    cohen_score = cohen_kappa_score(y_dev1, pred)
    print("Cohen Score: ",cohen_score)
    ##### PREDICTING test values ######
    y_pred=model.predict_classes(X_test1)
    df = pd.DataFrame(y_pred, columns = ['result'])
    return df
    

In [51]:
df=predict(X_dev1,y_dev1,X_test1)

Accuracy: 61.215627
Loss: 179.500824
              precision    recall  f1-score   support

           0       0.22      0.19      0.21        52
           1       0.59      0.55      0.57       139
           2       0.69      0.74      0.72       321
           3       0.62      0.59      0.60       110
           4       0.49      0.46      0.48        69

    accuracy                           0.61       691
   macro avg       0.52      0.51      0.52       691
weighted avg       0.60      0.61      0.61       691

Cohen Score:  0.4390826043761662


In [52]:
df

result
0         4
1         2
2         2
3         3
4         2
..      ...
763       1
764       0
765       2
766       0
767       0

[768 rows x 1 columns]

In [54]:
FINAL=pd.concat([Test_Data.Msg_without_Stopwords, df], axis=1)
FINAL=FINAL.rename(columns={"Msg_without_Stopwords": "text", "result": "label"})

FINAL['label'] = FINAL['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Kannada', 4 : 'unknown_state'})
FINAL[76:87]

text        label
76              Namma galli goo bandiddru ashwatthama     Positive
77          ಅವಾಗ ಕಬ್ಜ ದರ್ಶನ ಇವ್ರೆಲ್ಲಾ ಬಂದು ಕೆಡವಕ್ತಾರೆ     Positive
78                Hahahaha LoL nIdiot beggar get lost  not-Kannada
79  ಲಾಕ್ ಡೌನ್ ಸಮಯದಲ್ಲಿ ಕಾರ್ಮಿಕರು ವಲಸಿಗರು ರೆಸ್ತೆ ಮೇ...     Positive
80  ಮ್ಯೂಸಿಕ್ ಡೈರೆಕ್ಟರ್ ಗೆ ಒಂದು ದೊಡ್ಡ ಸಲಾಂ ಯಾವುದೋ ಲ...     Positive
81                         Fan war shuru madbeda guru     Positive
82              adeno gottilla tumba ista ayta nimage     Positive
83                            ಹೊಸ ಪ್ರಯೋಗ ಯಶಸ್ಸು ಸಿಗಲಿ     Positive
84                              ಹೌದೋ ಹುಲಿಯಾಹಾಡು ಸೂಪರ್     Positive
85  Ŕävîñđŕå GøWđřú neenu beedhi soole maga neene ...     Negative
86                                 Gandu loafer jeena     Negative

In [55]:
FINAL.to_csv("ANN_Kannada_HASOC21.tsv")

In [91]:
#from sklearn.metrics import confusion_matrix, classification_report
#from sklearn.metrics import cohen_kappa_score


#def emoji(y_Dev, X_Dev1, model): 
  # y_Dev1 = to_categorical(y_Dev)
 #   loss, accuracy = model.evaluate(X_Dev1,y_Dev, verbose=0)
  #  print('Accuracy: %f' % (accuracy*100))
   # print('Loss: %f' % (loss*100))
    #
    #y_pred=model.predict_classes(X_Dev1)

    
    # predict 
    #predictions = model.predict(X_Dev1, batch_size = 32)
    #pred = np.argmax(predictions, axis=1)
    # label
    #y_Dev1 = np.argmax(y_Dev, axis=1)
    
   # print(classification_report(y_Dev1, pred))
    
    #cohen_score = cohen_kappa_score(y_Dev1, pred)
    #print("Cohen Score: ",cohen_score)

In [92]:
#emoji(y_dev1, X_dev1, model)

Accuracy: 66.647792
Loss: 921.951864
              precision    recall  f1-score   support

           0       0.44      0.36      0.40       102
           1       0.60      0.52      0.56       237
           2       0.71      0.80      0.75       706
           3       0.76      0.52      0.62       141
           4       0.65      0.65      0.65       580

    accuracy                           0.67      1766
   macro avg       0.63      0.57      0.60      1766
weighted avg       0.66      0.67      0.66      1766

Cohen Score:  0.5158853789727409


In [51]:
from imblearn.over_sampling import SMOTE
smote = SMOTE('minority')


X_sm, y_sm = smote.fit_sample(X_train1, y_train1)
print(X_sm.shape, y_sm.shape)

e:\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=minority as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


(8461, 10000) (8461, 5)


e:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0 1 2 3 4] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [52]:
history = model.fit(X_sm, y_sm, batch_size=batch_size, epochs=num_epochs,verbose=2)

Train on 8461 samples
Epoch 1/10
8461/8461 - 4s - loss: 0.1296 - accuracy: 0.9579
Epoch 2/10
8461/8461 - 4s - loss: 0.1151 - accuracy: 0.9630
Epoch 3/10
8461/8461 - 4s - loss: 0.1097 - accuracy: 0.9632
Epoch 4/10
8461/8461 - 4s - loss: 0.1095 - accuracy: 0.9628
Epoch 5/10
8461/8461 - 4s - loss: 0.1001 - accuracy: 0.9650
Epoch 6/10
8461/8461 - 4s - loss: 0.0975 - accuracy: 0.9656
Epoch 7/10
8461/8461 - 4s - loss: 0.0979 - accuracy: 0.9666
Epoch 8/10
8461/8461 - 4s - loss: 0.0883 - accuracy: 0.9666
Epoch 9/10
8461/8461 - 4s - loss: 0.0894 - accuracy: 0.9680
Epoch 10/10
8461/8461 - 4s - loss: 0.0884 - accuracy: 0.9670


In [53]:
X_Dev_sm, y_Dev_sm = smote.fit_sample(X_dev1, y_dev1)
print(X_Dev_sm.shape, y_Dev_sm.shape)

(960, 10000) (960, 5)


e:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0 1 2 3 4] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [54]:
df_smote=predict(X_Dev_sm,y_Dev_sm,X_test1)

Accuracy: 58.854169
Loss: 245.261377
              precision    recall  f1-score   support

           0       0.68      0.55      0.61       321
           1       0.58      0.45      0.50       139
           2       0.55      0.74      0.64       321
           3       0.62      0.56      0.59       110
           4       0.40      0.35      0.37        69

    accuracy                           0.59       960
   macro avg       0.57      0.53      0.54       960
weighted avg       0.60      0.59      0.58       960

Cohen Score:  0.4332973664467805


#  https://shrikar.com/deep-learning-with-keras-and-python-for-multiclass-classification/

# CNN F1 score = 0.61


In [56]:
from keras.preprocessing.text import Tokenizer

In [57]:
word_tokenizer= Tokenizer()

# Train, Dev, Test
word_tokenizer.fit_on_texts(Train_Data.Msg_without_Stopwords)


In [58]:
max_length = max([len(s.split()) for s in Train_Data.Msg_without_Stopwords])
max_length

92

In [59]:
# define vocabulary size

vocab_size = len(word_tokenizer.word_index) + 1
vocab_size

15800

In [60]:
# Embeded Sentences of Train
Train_Sent = word_tokenizer.texts_to_sequences(Train_Data.Msg_without_Stopwords)

# Embeded Sentences of Dev
Dev_Sent = word_tokenizer.texts_to_sequences(Dev_Data.Msg_without_Stopwords)

# Embeded Sentences of Test
Test_Sent = word_tokenizer.texts_to_sequences(Test_Data.Msg_without_Stopwords)

In [61]:
from keras.preprocessing.sequence import pad_sequences


In [62]:
# X_train
Train_padded_sentences = pad_sequences(Train_Sent, max_length, padding='post')

# Dev
Dev_padded_sentences = pad_sequences(Dev_Sent, max_length, padding='post')

# Test
Test_padded_sentences = pad_sequences(Test_Sent, max_length, padding='post')

In [63]:
Train_Sent[0],Train_padded_sentences[0]

([82,
  269,
  4435,
  840,
  4436,
  4437,
  4438,
  270,
  4439,
  326,
  4440,
  4441,
  4442,
  1153,
  4443,
  76,
  171,
  4444,
  194,
  4445],
 array([  82,  269, 4435,  840, 4436, 4437, 4438,  270, 4439,  326, 4440,
        4441, 4442, 1153, 4443,   76,  171, 4444,  194, 4445,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]))

In [79]:
model_CNN = keras.Sequential([
    keras.layers.Embedding(vocab_size, 100, input_length=max_length),
   # keras.layers.GlobalAveragePooling1D(),
    # convolutional filters=128,  kernel size=3: it means length_long_sentence size of 65 we are luking for 3 words at a time
    keras.layers.Conv1D(64, 3, activation='relu'),
    keras.layers.GlobalMaxPooling1D(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(5, activation='softmax')
])



model_CNN.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_CNN.summary()



#model = Sequential()
#model.add(Embedding(vocab_size, 100, input_length=max_length))
#model.add(Conv1D(filters=32, kernel_size=8, activation='relu'))
#model.add(MaxPooling1D(pool_size=2))
#model.add(Flatten())
#model.add(Dense(10, activation='relu'))
#model.add(Dense(1, activation='sigmoid'))

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 92, 100)           1580000   
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 90, 64)            19264     
_________________________________________________________________
global_max_pooling1d_4 (Glob (None, 64)                0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 325       
Total params: 1,599,589
Trainable params: 1,599,589
Non-trainable params: 0
_________________________________________________________________


In [80]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 

In [81]:
from keras.utils import to_categorical
y_train=Train_Data['Nlabel']
y_dev=Dev_Data['Nlabel']

y_train1 = to_categorical(y_train)
y_dev1 = to_categorical(y_dev)

In [82]:
Train_padded_sentences.shape, y_train1.shape, Dev_padded_sentences.shape, y_dev1.shape, Test_padded_sentences.shape

((6212, 92), (6212, 5), (691, 92), (691, 5), (768, 92))

In [83]:
type(y_train1), type(Train_padded_sentences), type(Dev_padded_sentences), type(y_dev1), type(Test_padded_sentences)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [84]:
Train_padded_sentences=np.array(Train_padded_sentences)
y_train1=np.array(y_train1)

Train_padded_sentences.shape, y_train1.shape

((6212, 92), (6212, 5))

In [85]:
num_epochs =5
batch_size = 128
history = model_CNN.fit(Train_padded_sentences, y_train1, batch_size=batch_size, epochs=num_epochs, verbose=2)

Train on 6212 samples
Epoch 1/5
6212/6212 - 4s - loss: 1.4687 - accuracy: 0.4240
Epoch 2/5
6212/6212 - 3s - loss: 1.3323 - accuracy: 0.4731
Epoch 3/5
6212/6212 - 3s - loss: 1.1211 - accuracy: 0.5658
Epoch 4/5
6212/6212 - 3s - loss: 0.8743 - accuracy: 0.6937
Epoch 5/5
6212/6212 - 3s - loss: 0.6639 - accuracy: 0.7986


In [86]:
Dev_padded_sentences=np.array(Dev_padded_sentences)
y_dev1=np.array(y_dev1)

In [87]:
def predict_CNN(X_dev1,y_dev1,X_test1):
    loss, accuracy = model_CNN.evaluate(X_dev1,y_dev1,verbose=0)
    print('Accuracy: %f' % (accuracy*100))
    print('Loss: %f' % (loss*100))
    y_pred=model_CNN.predict_classes(X_dev1)

    # predict 
    predictions = model_CNN.predict(X_dev1, batch_size = 32)
    pred = np.argmax(predictions, axis=1)
    # label
    y_dev1 = np.argmax(y_dev1, axis=1)
    
    print(classification_report(y_dev1, pred))
    
    cohen_score = cohen_kappa_score(y_dev1, pred)
    print("Cohen Score: ",cohen_score)
    ##### PREDICTING test values ######
    y_pred=model_CNN.predict_classes(X_test1)
    df = pd.DataFrame(y_pred, columns = ['result'])
    return df

In [89]:
df_CNN=predict_CNN(Dev_padded_sentences,y_dev1,Test_padded_sentences)

Accuracy: 63.531113
Loss: 95.899139
              precision    recall  f1-score   support

           0       0.62      0.10      0.17        52
           1       0.64      0.56      0.60       139
           2       0.67      0.83      0.74       321
           3       0.60      0.62      0.61       110
           4       0.46      0.32      0.38        69

    accuracy                           0.64       691
   macro avg       0.60      0.48      0.50       691
weighted avg       0.63      0.64      0.61       691

Cohen Score:  0.4488883262386657


In [91]:
FINAL_CNN=pd.concat([Test_Data.Msg_without_Stopwords, df_CNN], axis=1)
FINAL_CNN=FINAL_CNN.rename(columns={"Msg_without_Stopwords": "text", "result": "label"})

FINAL_CNN['label'] = FINAL_CNN['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Kannada', 4 : 'unknown_state'})
FINAL[76:87]

text        label
76              Namma galli goo bandiddru ashwatthama     Positive
77          ಅವಾಗ ಕಬ್ಜ ದರ್ಶನ ಇವ್ರೆಲ್ಲಾ ಬಂದು ಕೆಡವಕ್ತಾರೆ     Positive
78                Hahahaha LoL nIdiot beggar get lost  not-Kannada
79  ಲಾಕ್ ಡೌನ್ ಸಮಯದಲ್ಲಿ ಕಾರ್ಮಿಕರು ವಲಸಿಗರು ರೆಸ್ತೆ ಮೇ...     Positive
80  ಮ್ಯೂಸಿಕ್ ಡೈರೆಕ್ಟರ್ ಗೆ ಒಂದು ದೊಡ್ಡ ಸಲಾಂ ಯಾವುದೋ ಲ...     Positive
81                         Fan war shuru madbeda guru     Positive
82              adeno gottilla tumba ista ayta nimage     Positive
83                            ಹೊಸ ಪ್ರಯೋಗ ಯಶಸ್ಸು ಸಿಗಲಿ     Positive
84                              ಹೌದೋ ಹುಲಿಯಾಹಾಡು ಸೂಪರ್     Positive
85  Ŕävîñđŕå GøWđřú neenu beedhi soole maga neene ...     Negative
86                                 Gandu loafer jeena     Negative

In [92]:
FINAL_CNN.to_csv("CNN_Kannada_HASOC21.tsv")

In [310]:
#emoji(y_dev1, Dev_padded_sentences, model_CNN)

In [84]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, GRU
from keras.layers.embeddings import Embedding

In [122]:
# step 1
embedding_matrix = np.zeros((vocab_size, 300)) #create an array of zeros with word_num rows and embedding_dim columns

# step 2 & step 3
for word, index in word_tokenizer.word_index.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        embedding_matrix[index] = embedding_vector


NameError: name 'embeddings_dictionary' is not defined

In [85]:
lstm_node=32
nclasses=5

In [86]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dropout, Dense, Embedding, LSTM, Bidirectional

In [144]:
model_BiLSTM=keras.Sequential([
     # add Embeddign layer
keras.layers.Embedding(vocab_size,300, input_length=max_length, trainable=True),
    # add birectional 
keras.layers.Bidirectional(LSTM(lstm_node, return_sequences=True, recurrent_dropout=0.2)),
    # add dropout layer after  each lstm
keras.layers.Dropout(0.2),
        # add birectional 
keras.layers.Bidirectional(LSTM(lstm_node, recurrent_dropout=0.2)),
     # add dropout layer after  each lstm
keras.layers.Dropout(0.2),
    # Add the fully connected layer with 256 nurons and relu activation
keras.layers.Dense(256,activation='relu'),
    # Add the output layer with softmax activation since we have 2 classes
keras.layers.Dense(nclasses, activation='softmax')
])

model_BiLSTM.compile(loss='sparse_categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])
model_BiLSTM.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 195, 300)          12069000  
_________________________________________________________________
bidirectional_6 (Bidirection (None, 195, 64)           85248     
_________________________________________________________________
dropout_9 (Dropout)          (None, 195, 64)           0         
_________________________________________________________________
bidirectional_7 (Bidirection (None, 64)                24832     
_________________________________________________________________
dropout_10 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 256)               16640     
_________________________________________________________________
dense_11 (Dense)             (None, 5)                

In [145]:
Train_padded_sentences, Train_padded_sentences.shape

(array([[  398,   399,     9, ...,     0,     0,     0],
        [  179,  3473,  3474, ...,     0,     0,     0],
        [  194,   253,   813, ...,     0,     0,     0],
        ...,
        [ 1871,   696,   787, ...,     0,     0,     0],
        [11438,   453,  1582, ...,     0,     0,     0],
        [  543,  2190,    25, ...,     0,     0,     0]]), (15888, 195))

In [146]:
y_train1, y_train1.shape

(array([[0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.]]), (15888, 5))

In [147]:
Train_padded_sentences.shape, y_train1.shape

((15888, 195), (15888, 5))

In [164]:
Train_padded_sentences.shape, Train_Data['Nlabel'].shape, type(Train_padded_sentences), type(Train_Data['Nlabel'])

((15888, 195), (15888,), numpy.ndarray, pandas.core.series.Series)

In [168]:
train_y=Train_Data['Nlabel'].to_numpy()
type(train_y), type(y_train1)

(numpy.ndarray, numpy.ndarray)

In [170]:
history = model_BiLSTM.fit(Train_padded_sentences, y_train1, batch_size=batch_size, epochs=num_epochs, verbose=2)

Train on 15888 samples
Epoch 1/10


TypeError: 'NoneType' object is not callable

# One Hot : Bilstem

In [94]:
from tensorflow.keras.preprocessing.text import one_hot

# train

In [99]:
onehot_repr=[one_hot(words,vocab_size)for words in Train_Data.Msg_without_Stopwords] 
onehot_repr

[[14089,
  1935,
  6247,
  4205,
  9451,
  15145,
  413,
  13213,
  9181,
  6348,
  6796,
  3009,
  9210,
  15433,
  4628,
  1930,
  2868,
  5087,
  5674,
  15473],
 [1279, 1218, 1408, 13058, 6981, 12855, 3774, 14666, 5838],
 [10706, 5709, 9706],
 [3541, 14847, 12089, 10652, 5768, 14666, 5743],
 [10706, 9186, 3644, 15324],
 [9814,
  5174,
  14948,
  683,
  344,
  8103,
  2285,
  6333,
  13024,
  4043,
  1960,
  14114,
  14805,
  6501,
  15339,
  2433,
  6927,
  7454,
  2285,
  3935,
  9763,
  5925,
  11599,
  5097,
  4074,
  1960,
  14835],
 [7691, 5956, 12306, 130, 285, 12005],
 [10706, 10706, 10706, 7454, 13144, 12737, 2320],
 [9302, 10672, 14068, 2303, 15115, 3529],
 [8547, 2515, 10706],
 [708, 7982, 13430, 15716, 14143],
 [15319, 685],
 [4166, 3703, 4990],
 [1103, 3264, 3078, 10405, 8431, 6309],
 [72, 15788, 5575, 8243, 12813],
 [7429, 13904, 5992, 11697, 1990, 13170, 10927],
 [3949,
  11511,
  14126,
  10166,
  8858,
  3104,
  9189,
  1103,
  7739,
  14702,
  14374,
  14299],
 [47

In [100]:
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=195)
print(embedded_docs)

[[14089  1935  6247 ...     0     0     0]
 [ 1279  1218  1408 ...     0     0     0]
 [10706  5709  9706 ...     0     0     0]
 ...
 [15408  7330 10050 ...     0     0     0]
 [13350  1406  1777 ...     0     0     0]
 [ 4888 12827     0 ...     0     0     0]]


In [101]:
embedded_docs.shape, y_train1.shape

((6212, 195), (6212, 5))

# Dev

In [102]:
onehot_repr1=[one_hot(words,vocab_size)for words in Dev_Data.Msg_without_Stopwords] 
len(onehot_repr1)

691

In [103]:
embedded_docs_dev=pad_sequences(onehot_repr1,padding='post',maxlen=195)
len(embedded_docs_dev)

691

In [104]:
y_dev1

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [105]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y_train1)

x_dev_final=np.array(embedded_docs_dev)
y_dev_final=np.array(y_dev1)

In [106]:
len(x_dev_final)

691

In [107]:
X_final.shape, y_final.shape, x_dev_final.shape, y_dev_final.shape

((6212, 195), (6212, 5), (691, 195), (691, 5))

In [108]:
from tensorflow.python.keras.layers import Dropout, Dense, Embedding, LSTM, Bidirectional
model_CNN1 = keras.Sequential([
    keras.layers.Embedding(vocab_size, 50, input_length=max_length),
   # keras.layers.GlobalAveragePooling1D(),
    # convolutional filters=128,  kernel size=3: it means length_long_sentence size of 65 we are luking for 3 words at a time
    keras.layers.Conv1D(756, 7, activation='relu'),
    keras.layers.Conv1D(756, 7, activation='relu'),
    keras.layers.MaxPool1D(),
    keras.layers.Conv1D(256, 3, activation='relu'),
    keras.layers.Conv1D(256, 3, activation='relu'),
    keras.layers.MaxPool1D(),
    keras.layers.Bidirectional(LSTM(400)),
    keras.layers.Dense(5, activation='softmax')
])

model_CNN1.compile(loss='sparse_categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])
model_CNN1.summary()

NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array.

In [ ]:
model_CNN1.fit(X_final,y_final,epochs=10,batch_size=64)

In [113]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(vocab_size,embedding_vector_features,input_length=195))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(5,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 195, 40)           1609200   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_6 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 1005      
Total params: 1,723,005
Trainable params: 1,723,005
Non-trainable params: 0
_________________________________________________________________
None


In [114]:
model1.fit(X_final,y_final,epochs=10,batch_size=64)

Train on 15888 samples
Epoch 1/10
15888/15888 [==============================] - 2813s 177ms/sample - loss: 0.4279 - accuracy: 0.8112
Epoch 2/10
15888/15888 [==============================] - 1174s 74ms/sample - loss: 0.2807 - accuracy: 0.8847
Epoch 3/10
15888/15888 [==============================] - 1182s 74ms/sample - loss: 0.1715 - accuracy: 0.9341
Epoch 4/10
15888/15888 [==============================] - 2292s 144ms/sample - loss: 0.1099 - accuracy: 0.9619
Epoch 5/10
15888/15888 [==============================] - 1207s 76ms/sample - loss: 0.0656 - accuracy: 0.9788
Epoch 6/10
15888/15888 [==============================] - 1194s 75ms/sample - loss: 0.0479 - accuracy: 0.9850
Epoch 7/10
15888/15888 [==============================] - 1190s 75ms/sample - loss: 0.0377 - accuracy: 0.9888
Epoch 8/10
15888/15888 [==============================] - 812s 51ms/sample - loss: 0.0311 - accuracy: 0.9900
Epoch 9/10
15888/15888 [==============================] - 803s 51ms/sample - loss: 0.0261 - accu

In [139]:
emoji(y_dev_final, x_dev_final, model1)

Accuracy: 86.557204
Loss: 55.181224
              precision    recall  f1-score   support

           0       0.34      0.37      0.35       102
           1       0.64      0.43      0.51       237
           2       0.69      0.74      0.71       706
           3       0.71      0.68      0.69       141
           4       0.65      0.67      0.66       580

    accuracy                           0.65      1766
   macro avg       0.60      0.58      0.59      1766
weighted avg       0.65      0.65      0.65      1766

Cohen Score:  0.495450229923202


In [104]:
Train_padded_sentences.shape, y_train1.shape, y_dev1.shape, Dev_padded_sentences.shape

((15888, 195), (15888, 5), (1766, 5), (1766, 195))