In [1]:
from sklearn.datasets import load_files
import pandas as pd

In [2]:
#Malayalam
Mal_train=pd.read_csv("Mal_sentiment_full_train.tsv", sep='\t')


Mal_Dev=pd.read_csv("Mal_sentiment_full_dev.tsv", sep='\t')


Mal_test=pd.read_csv("Mal_sentiment_full_test_withoutlabels.tsv", sep='\t')

In [3]:
Mal_train.shape, Mal_Dev.shape, Mal_test.shape

((15888, 2), (1766, 2), (1962, 2))

In [4]:
Mal_Dev.head()

text       category
0                Mammooka ninghal mass aa pwoli item       Positive
1      Waiting for Malayalam movie  For Tamil paiyan  not-malayalam
2     ദളപതി ഫാൻസിന്റെ വക ഒരു ഒന്നൊന്നര വിജയാശംസകൾ...       Positive
3  #Trailer pwolichuuuu ഓണത്തിന് വന്നങ്ങു തകർത്തേ...       Positive
4   Mammoookkaaaa polichadukkiii katta waiting nv 21       Positive

In [5]:
from ml2en import ml2en

In [6]:
converter = ml2en()

desti_lang={
     'malayalam' : 'ml'
}

In [7]:
for key,value in desti_lang.items():
     #print(transt.translate(Mal_train['text']))
        Mal_train['text1']=Mal_train['text'].apply(lambda x: converter.transliterate(x))
        Mal_Dev['text1']=Mal_Dev['text'].apply(lambda x: converter.transliterate(x))
        Mal_test['text1']=Mal_test['text'].apply(lambda x: converter.transliterate(x))

In [8]:
Mal_train[61:70]

text       category  \
61  ചുമ്മാതല്ല Anurag Kashyap മച്ചാൻ കാശ് ഇറക്കിയത...       Positive   
62  ട്രെയ്‌ലർ പൊളിച്ചു.... ഇനി പടം കൂടി പൊളിച്ചാൽ ...       Positive   
63  ഈ വൃത്തികെട്ടവൻ തന്നെയാണോ ബിഗ്‌ബിയിൽ bgm ചെയ്ത...       Negative   
64                     ആ PSYCHO ചിരിക്ക് കൊടുക്ക് ഒരു  unknown_state   
65  Shung shing sung onamshang vashang (appo onath...  unknown_state   
66  ഇതാണോ നിന്റെ പുകയില്ലാത്ത അടുപ്പു, ദേ ഞാൻ അങ്ങ...  unknown_state   
67  Irakikko pakshe Stephen achayan ullidatholam k...       Negative   
68  Trailer il thanne full story undallo! Padam ki...  unknown_state   
69  Tollywood - Bahubali  Kollywood - 2.O Sandalwo...  not-malayalam   

                                                text1  
61  Chummaathalla anurag kashyap macchaan kaashu i...  
62  Trey‌lar policchu.... Ini patam kooti policcha...  
63  Ee vrutthikettavan thanneyaano big‌biyil bgm c...  
64                     Aa psycho chirikku kotukku oru  
65  Shung shing sung onamshang vashang (appo onath...  
66  Ithaano ninte pukayillaattha atuppu, de njaan ...  
67  Irakikko pakshe stephen achayan ullidatholam k...  
68  Trailer il thanne full story undallo! Padam ki...  
69  Tollywood - bahubali  kollywood - 2.O sandalwo...

In [9]:
Mal_Dev.head()

text       category  \
0                Mammooka ninghal mass aa pwoli item       Positive   
1      Waiting for Malayalam movie  For Tamil paiyan  not-malayalam   
2     ദളപതി ഫാൻസിന്റെ വക ഒരു ഒന്നൊന്നര വിജയാശംസകൾ...       Positive   
3  #Trailer pwolichuuuu ഓണത്തിന് വന്നങ്ങു തകർത്തേ...       Positive   
4   Mammoookkaaaa polichadukkiii katta waiting nv 21       Positive   

                                               text1  
0                Mammooka ninghal mass aa pwoli item  
1      Waiting for malayalam movie  for tamil paiyan  
2  Dalapathi phaansinte vaka oru onnonnara vijaya...  
3  #trailer pwolichuuuu onatthinu vannangu thakar...  
4   Mammoookkaaaa polichadukkiii katta waiting nv 21

In [10]:
Mal_test.head()

id                                               text  \
0  Mal_1  Teaserinu kurach samayamkoodi mathram. Cant wa...   
1  Mal_2                 അപ്പോൾ കഥയുടെ  റൂട്ട് മാറിയല്ലോ...   
2  Mal_3     മൂത്തോൻ ട്രൈലെർ Trending List വരാത്തത് എന്താ ?   
3  Mal_4  Nowadays 944k views is considered as 1M views ...   
4  Mal_5  Maass.trailer ennu paranja ithaanU makkale.......   

                                               text1  
0  Teaserinu kurach samayamkoodi mathram. Cant wa...  
1              Appol kathayute  roottu maariyallo...  
2  Mootthon tryler trending list varaatthathu ent...  
3  Nowadays 944k views is considered as 1m views ...  
4  Maass.Trailer ennu paranja ithaanu makkale.......

In [11]:
# Train
Mal_train['category'].value_counts()

Positive          6421
unknown_state     5279
Negative          2105
not-malayalam     1157
Mixed_feelings     926
Name: category, dtype: int64

In [12]:
# Development 
Mal_Dev['category'].value_counts()

Positive          706
unknown_state     580
Negative          237
not-malayalam     141
Mixed_feelings    102
Name: category, dtype: int64

In [13]:
msg=Mal_train['text1']

msgDev=Mal_Dev['text1']

msgTest=Mal_test['text1']

In [14]:
msgDev[50:70]

50    Njaan padticcha skool njaan padticcha klaas‌ a...
51    Pheeldauttu‌  nikker salman fans vannu karanju...
52    Aashaya daaridram piticcha ezhutthukaarotu puc...
53    100 crore box office gross collection netiyath...
54    59 vayasilum ingane maargam kalikkaan laaletta...
55    Trailer evidakkayo katha muyavanayum kanikkunn...
56         Ee pennungalkku kannu kaanaanille...  Shava൦
57    Jojoyute chettante abhinayao athu oru athbhuda...
58    Oru katta mammookka phaan aaya njaan mukkutthi...
59                        Promo kand kili poya le njaan
60    Ith kidukkum.. Ellarum abhinayikkunath pole fe...
61    Allelum tcr besu cheythu patam irakkiyo athu g...
62                        Thalaivaaa 🤩 🤩🤩 🤩🤩 🤩🤩 🤩🤩 🤩🤩 🤩
63    Mattannaal varunna teaser nu ippozhe katta wai...
64    Karikkile lolante premam kandittundo  onnu kan...
65    Aa urumi karakki adikkunnathu woe romangification
66    Trailer video polum puratthu varunnathinu munn...
67    Nammute ikka ee praavashyam varunnathu bok

In [15]:
Mal_train['text1']

0        Sunny chechi fans evide like adichu power kani...
1        Angane july month ile ende aadyathe leave njan...
2        Ettante puthiya patatthinu vendi kaatthirikkun...
3        Ini laalettante vetta thutangaan pokunnu.........
4        Trailer powli oru raksha illa . Pakshea padam ...
                               ...                        
15883        Minimum 10 thavana kandavar maathram like adi
15884    Please cinema kaannaaan kothi aakunnu onnu rel...
15885                     Usa ok.. India no... Sadhacharam
15886    Nama hero december 12 wait & see  mamamaga mah...
15887    Madhuraraja 1 hour 40 k likes  lucifer 1 min 4...
Name: text1, Length: 15888, dtype: object

In [16]:
#Remove Emojis

def emoji(msg): 
    
    msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
    
    msg_digit=msg_emoj.str.replace(r'[0-9]', ' ')

    msg_Spac = msg_digit.str.replace(r'_',' ')

    msg_Spac = msg_Spac.str.replace(r'.','')

    msg_Spac = msg_Spac.str.replace(r'!','')

    msg_Spac = msg_Spac.str.replace(r'#','')

    msg_Spac = msg_Spac.str.replace(r'%','')

    msg_Spac = msg_Spac.str.replace(r'&','')

    msg_Spac = msg_Spac.str.replace(r'’','')

    msg_Spac = msg_Spac.str.replace(r'(','')

    msg_Spac = msg_Spac.str.replace(r')','')

    msg_Spac = msg_Spac.str.replace(r'-','')

    msg_Spac = msg_Spac.str.replace(r'/','')

    msg_Spac = msg_Spac.str.replace(r':','')

    msg_Spac = msg_Spac.str.replace(r';','')

    msg_Spac = msg_Spac.str.replace(r'<','')

    msg_Spac = msg_Spac.str.replace(r'=','')

    msg_Spac = msg_Spac.str.replace(r'>','')

    msg_Spac = msg_Spac.str.replace(r'?','')

    msg_Spac = msg_Spac.str.replace(r'@','')

    msg_Spac = msg_Spac.str.replace(r'[','')

    msg_Spac = msg_Spac.str.replace(r']','')

    msg_Spac = msg_Spac.str.replace(r'^','')

    msg_Spac = msg_Spac.str.replace(r'{','')

    msg_Spac = msg_Spac.str.replace(r'}','')

    msg_Spac = msg_Spac.str.replace(r'|','')

    msg_Spac = msg_Spac.str.replace(r'~','')

    msg_Spac = msg_Spac.str.replace(r'+','')

    msg_Spac = msg_Spac.str.replace(r'\s+', ' ')


    return msg_Spac
    

In [17]:
msg_Train=emoji(msg)

msg_Dev=emoji(msgDev)

msg_Test=emoji(msgTest)

e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: The default value of regex will c

In [18]:
msg_Test.head()

0      Teaserinu kurach samayamkoodi mathram Cant wait
1                    Appol kathayute roottu maariyallo
2    Mootthon tryler trending list varaatthathu ent...
3    Nowadays k views is considered as m views in k...
4    MaassTrailer ennu paranja ithaanu makkaleKatta...
Name: text1, dtype: object

In [19]:
msg_Train[78:90], msg_Dev[50:70], msg_Test[21:22]


(78    Ikkayute sthreevesham kandu kampi ayavarkkum p...
 79    Unnni mukundante padamenn paranj arenkilum van...
 80        Nyc but best actor poley aayaaal seriyaavilla
 81                       m views k likes triple strongg
 82      le aadya bombu nte kaaryatthil theerumaanamaayi
 83    Mammookka phaansinte ellaam vidha vijaya aasha...
 84    Maasu kotoora maasu athaanu kolla palisha kaar...
 85       Mammookka phaan aaya njaan polum lykku aticchu
 86    Mammunniyepole oliporallithu eathu yudham vann...
 87             Enta joju etta ningalithe ende bhavichaa
 88    Veendum veendum tryler kaanaan varunnavar undo...
 89     Ejjathi level sadhanam ishttappettavar like adik
 Name: text1, dtype: object,
 50    Njaan padticcha skool njaan padticcha klaas‌ a...
 51    Pheeldauttu‌ nikker salman fans vannu karanju ...
 52    Aashaya daaridram piticcha ezhutthukaarotu puc...
 53     crore box office gross collection netiyathari...
 54     vayasilum ingane maargam kalikkaan laalettane...
 5

In [20]:
Train_Df=pd.DataFrame(msg_Train)
Train_Df.columns=['Msg_with_Stopwords']

Dev_Df=pd.DataFrame(msg_Dev)
Dev_Df.columns=['Msg_with_Stopwords']

Test_Df=pd.DataFrame(msg_Test)
Test_Df.columns=['Msg_with_Stopwords']

In [21]:
Train_Df.shape, Dev_Df.shape, Test_Df.shape

((15888, 1), (1766, 1), (1962, 1))

In [22]:
# Removing Null Values

Train_Df['Msg_with_Stopwords']=Train_Df['Msg_with_Stopwords'].fillna("")

Dev_Df['Msg_with_Stopwords']=Dev_Df['Msg_with_Stopwords'].fillna("")

Test_Df['Msg_with_Stopwords']=Test_Df['Msg_with_Stopwords'].fillna("")


In [23]:
Mal_train.shape, Mal_Dev.shape,Train_Df.shape, Dev_Df.shape, Mal_test.shape, Test_Df.shape

((15888, 3), (1766, 3), (15888, 1), (1766, 1), (1962, 3), (1962, 1))

In [24]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Joshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [25]:
stop_words = set(stopwords.words('english'))

In [26]:
Train_Df['Msg_without_Stopwords']=Train_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Dev_Df['Msg_without_Stopwords']=Dev_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Test_Df['Msg_without_Stopwords']=Test_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [27]:
Train_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_with_Stopwords'].tolist()]
Train_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_without_Stopwords'].tolist()]

Dev_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_with_Stopwords'].tolist()]
Dev_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_without_Stopwords'].tolist()]

Test_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_with_Stopwords'].tolist()]
Test_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_without_Stopwords'].tolist()]

In [28]:
Train_Data=pd.concat([Mal_train, Train_Df], axis=1)

Dev_Data=pd.concat([Mal_Dev, Dev_Df], axis=1)

Test_Data=pd.concat([Mal_test, Test_Df], axis=1)

In [29]:
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((15888, 7), (1766, 7), (1962, 7))

In [30]:
Test_Data

id                                               text  \
0        Mal_1  Teaserinu kurach samayamkoodi mathram. Cant wa...   
1        Mal_2                 അപ്പോൾ കഥയുടെ  റൂട്ട് മാറിയല്ലോ...   
2        Mal_3     മൂത്തോൻ ട്രൈലെർ Trending List വരാത്തത് എന്താ ?   
3        Mal_4  Nowadays 944k views is considered as 1M views ...   
4        Mal_5  Maass.trailer ennu paranja ithaanU makkale.......   
...        ...                                                ...   
1957  Mal_1958  Expression വച്ചു നോക്കുമ്പോൾ മൂക്കുത്തി കട്ടത്...   
1958  Mal_1959                        എനിക്ക് ഒരു  100 like തരുമോ   
1959  Mal_1960  Nannayi onnu poliyunna lakshnm unde...Thrill m...   
1960  Mal_1961  Athikam eduthu kayatti vekkenda....direction k...   
1961  Mal_1962  Ithupole mooonchiya Oru padam jeevithathil kan...   

                                                  text1  \
0     Teaserinu kurach samayamkoodi mathram. Cant wa...   
1                 Appol kathayute  roottu maariyallo...   
2     Mootthon tryler trending list varaatthathu ent...   
3     Nowadays 944k views is considered as 1m views ...   
4     Maass.Trailer ennu paranja ithaanu makkale.......   
...                                                 ...   
1957  Expression vacchu nokkumpol mookkutthi kattath...   
1958                       Enikku oru  100 like tharumo   
1959  Nannayi onnu poliyunna lakshnm unde...Thrill m...   
1960  Athikam eduthu kayatti vekkenda....Direction k...   
1961  Ithupole mooonchiya oru padam jeevithathil kan...   

                                     Msg_with_Stopwords  \
0       Teaserinu kurach samayamkoodi mathram Cant wait   
1                     Appol kathayute roottu maariyallo   
2     Mootthon tryler trending list varaatthathu ent...   
3     Nowadays k views is considered as m views in k...   
4     MaassTrailer ennu paranja ithaanu makkaleKatta...   
...                                                 ...   
1957  Expression vacchu nokkumpol mookkutthi kattath...   
1958                            Enikku oru like tharumo   
1959  Nannayi onnu poliyunna lakshnm undeThrill main...   
1960  Athikam eduthu kayatti vekkendaDirection kke k...   
1961  Ithupole mooonchiya oru padam jeevithathil kan...   

                                  Msg_without_Stopwords  \
0       Teaserinu kurach samayamkoodi mathram Cant wait   
1                     Appol kathayute roottu maariyallo   
2     Mootthon tryler trending list varaatthathu enthaa   
3              Nowadays k views considered views kerala   
4     MaassTrailer ennu paranja ithaanu makkaleKatta...   
...                                                 ...   
1957  Expression vacchu nokkumpol mookkutthi kattath...   
1958                            Enikku oru like tharumo   
1959  Nannayi onnu poliyunna lakshnm undeThrill main...   
1960  Athikam eduthu kayatti vekkendaDirection kke k...   
1961  Ithupole mooonchiya oru padam jeevithathil kan...   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  
0                          6                          6  
1                          4                          4  
2                          6                          6  
3                         10                          6  
4                          8                          7  
...                      ...                        ...  
1957                      65                         64  
1958                       4                          4  
1959                       8                          8  
1960                      14                         14  
1961                       6                          6  

[1962 rows x 7 columns]

In [31]:
Train_Data=Train_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Dev_Data=Dev_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Test_Data=Test_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)


In [32]:
# Dataset Train & Dev are : (1) Message_Without_Stopwords and (2) labels
# Only Test is : (1) Message_Without_Stopwords
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((15888, 3), (1766, 3), (1962, 3))

In [33]:
Train_Data[78:90]

category                                              text1  \
78        Negative  Ikkayute sthreevesham kandu kampi ayavarkkum p...   
79   unknown_state  Unnni mukundante padamenn paranj arenkilum van...   
80  Mixed_feelings      Nyc but best actor poley aayaaal seriyaavilla   
81   not-malayalam              1.7m views 177k likes  triple strongg   
82        Negative  2020-le aadya bombu nte kaaryatthil theerumaan...   
83        Positive  Mammookka phaansinte ellaam vidha vijaya aasha...   
84        Positive  Maasu kotoora maasu athaanu kolla palisha kaar...   
85        Positive     Mammookka phaan aaya njaan polum lykku aticchu   
86        Negative  Mammunniyepole oliporallithu eathu yudham vann...   
87   unknown_state           Enta joju etta ningalithe ende bhavichaa   
88        Negative  Veendum veendum tryler kaanaan varunnavar undo...   
89        Positive  Ejjathi level sadhanam ishttappettavar like adik🥰   

                                Msg_without_Stopwords  
78  Ikkayute sthreevesham kandu kampi ayavarkkum p...  
79  Unnni mukundante padamenn paranj arenkilum van...  
80          Nyc best actor poley aayaaal seriyaavilla  
81                       views k likes triple strongg  
82    le aadya bombu nte kaaryatthil theerumaanamaayi  
83  Mammookka phaansinte ellaam vidha vijaya aasha...  
84  Maasu kotoora maasu athaanu kolla palisha kaar...  
85     Mammookka phaan aaya njaan polum lykku aticchu  
86  Mammunniyepole oliporallithu eathu yudham vann...  
87           Enta joju etta ningalithe ende bhavichaa  
88  Veendum veendum tryler kaanaan varunnavar undo...  
89   Ejjathi level sadhanam ishttappettavar like adik

In [34]:
Dev_Data

category                                              text1  \
0          Positive                Mammooka ninghal mass aa pwoli item   
1     not-malayalam      Waiting for malayalam movie  for tamil paiyan   
2          Positive  Dalapathi phaansinte vaka oru onnonnara vijaya...   
3          Positive  #trailer pwolichuuuu onatthinu vannangu thakar...   
4          Positive   Mammoookkaaaa polichadukkiii katta waiting nv 21   
...             ...                                                ...   
1761       Positive            Aa chiri uff ente ponno ikka vere leval   
1762       Positive   Katta katta katta katta waiting....Cant wait man   
1763  unknown_state  Arjun reddy bgm poole thonniyathu enniku mathr...   
1764       Positive             Fahad ikka ithilum polikum en urappayi   
1765       Positive  Njan veendum kanan vannu 100 pravashyam enkilu...   

                                  Msg_without_Stopwords  
0                   Mammooka ninghal mass aa pwoli item  
1                  Waiting malayalam movie tamil paiyan  
2     Dalapathi phaansinte vaka oru onnonnara vijaya...  
3     trailer pwolichuuuu onatthinu vannangu thakart...  
4         Mammoookkaaaa polichadukkiii katta waiting nv  
...                                                 ...  
1761            Aa chiri uff ente ponno ikka vere leval  
1762       Katta katta katta katta waitingCant wait man  
1763  Arjun reddy bgm poole thonniyathu enniku mathr...  
1764             Fahad ikka ithilum polikum en urappayi  
1765  Njan veendum kanan vannu pravashyam enkilum ka...  

[1766 rows x 3 columns]

In [35]:
Test_Data

id                                              text1  \
0        Mal_1  Teaserinu kurach samayamkoodi mathram. Cant wa...   
1        Mal_2              Appol kathayute  roottu maariyallo...   
2        Mal_3  Mootthon tryler trending list varaatthathu ent...   
3        Mal_4  Nowadays 944k views is considered as 1m views ...   
4        Mal_5  Maass.Trailer ennu paranja ithaanu makkale.......   
...        ...                                                ...   
1957  Mal_1958  Expression vacchu nokkumpol mookkutthi kattath...   
1958  Mal_1959                       Enikku oru  100 like tharumo   
1959  Mal_1960  Nannayi onnu poliyunna lakshnm unde...Thrill m...   
1960  Mal_1961  Athikam eduthu kayatti vekkenda....Direction k...   
1961  Mal_1962  Ithupole mooonchiya oru padam jeevithathil kan...   

                                  Msg_without_Stopwords  
0       Teaserinu kurach samayamkoodi mathram Cant wait  
1                     Appol kathayute roottu maariyallo  
2     Mootthon tryler trending list varaatthathu enthaa  
3              Nowadays k views considered views kerala  
4     MaassTrailer ennu paranja ithaanu makkaleKatta...  
...                                                 ...  
1957  Expression vacchu nokkumpol mookkutthi kattath...  
1958                            Enikku oru like tharumo  
1959  Nannayi onnu poliyunna lakshnm undeThrill main...  
1960  Athikam eduthu kayatti vekkendaDirection kke k...  
1961  Ithupole mooonchiya oru padam jeevithathil kan...  

[1962 rows x 3 columns]

In [36]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 

In [37]:
Train_Data['Nlabel'].value_counts()

2    6421
4    5279
1    2105
3    1157
0     926
Name: Nlabel, dtype: int64

In [38]:
Positive          6421 2
unknown_state     5279 4
Negative          2105 1
not-malayalam     1157 3
Mixed_feelings     926 0

Positive          706 2
unknown_state     580 4
Negative          237 1
not-malayalam     141 3
Mixed_feelings    102 0

SyntaxError: invalid syntax (<ipython-input-38-ae49b5ac1daf>, line 1)

In [39]:
Dev_Data['Nlabel'].value_counts()

2    706
4    580
1    237
3    141
0    102
Name: Nlabel, dtype: int64

In [40]:
Train_Data

category                                              text1  \
0       unknown_state  Sunny chechi fans evide like adichu power kani...   
1            Positive  Angane july month ile ende aadyathe leave njan...   
2       unknown_state  Ettante puthiya patatthinu vendi kaatthirikkun...   
3            Positive  Ini laalettante vetta thutangaan pokunnu.........   
4            Positive  Trailer powli oru raksha illa . Pakshea padam ...   
...               ...                                                ...   
15883   unknown_state      Minimum 10 thavana kandavar maathram like adi   
15884        Positive  Please cinema kaannaaan kothi aakunnu onnu rel...   
15885   unknown_state                   Usa ok.. India no... Sadhacharam   
15886        Positive  Nama hero december 12 wait & see  mamamaga mah...   
15887  Mixed_feelings  Madhuraraja 1 hour 40 k likes  lucifer 1 min 4...   

                                   Msg_without_Stopwords  Nlabel  
0       Sunny chechi fans evide like adichu power kaniku       4  
1      Angane july month ile ende aadyathe leave njan...       2  
2      Ettante puthiya patatthinu vendi kaatthirikkun...       4  
3      Ini laalettante vetta thutangaan pokunnu Mun k...       2  
4      Trailer powli oru raksha illa Pakshea padam ir...       2  
...                                                  ...     ...  
15883         Minimum thavana kandavar maathram like adi       4  
15884  Please cinema kaannaaan kothi aakunnu onnu rel...       2  
15885                           Usa ok India Sadhacharam       4  
15886  Nama hero december wait see mamamaga maha maga...       2  
15887       Madhuraraja hour k likes lucifer min k likes       0  

[15888 rows x 4 columns]

In [41]:
Dev_Data[50:70]

category                                              text1  \
50        Positive  Njaan padticcha skool njaan padticcha klaas‌ a...   
51        Negative  Pheeldauttu‌  nikker salman fans vannu karanju...   
52        Negative  Aashaya daaridram piticcha ezhutthukaarotu puc...   
53        Positive  100 crore box office gross collection netiyath...   
54        Positive  59 vayasilum ingane maargam kalikkaan laaletta...   
55  Mixed_feelings  Trailer evidakkayo katha muyavanayum kanikkunn...   
56        Negative       Ee pennungalkku kannu kaanaanille...  Shava൦   
57        Positive  Jojoyute chettante abhinayao athu oru athbhuda...   
58        Positive  Oru katta mammookka phaan aaya njaan mukkutthi...   
59   unknown_state                      Promo kand kili poya le njaan   
60        Positive  Ith kidukkum.. Ellarum abhinayikkunath pole fe...   
61        Positive  Allelum tcr besu cheythu patam irakkiyo athu g...   
62   not-malayalam                      Thalaivaaa 🤩 🤩🤩 🤩🤩 🤩🤩 🤩🤩 🤩🤩 🤩   
63        Positive  Mattannaal varunna teaser nu ippozhe katta wai...   
64   unknown_state  Karikkile lolante premam kandittundo  onnu kan...   
65        Positive  Aa urumi karakki adikkunnathu woe romangification   
66        Negative  Trailer video polum puratthu varunnathinu munn...   
67        Positive  Nammute ikka ee praavashyam varunnathu boksu‌ ...   
68   unknown_state  Lucifer film kandittu trailer kanunevar ethra ...   
69  Mixed_feelings  Nylaykku pattuvo? Thumpiye kondu kallu etuppiy...   

                                Msg_without_Stopwords  Nlabel  
50  Njaan padticcha skool njaan padticcha klaas‌ a...       2  
51  Pheeldauttu‌ nikker salman fans vannu karanju ...       1  
52  Aashaya daaridram piticcha ezhutthukaarotu puc...       1  
53  crore box office gross collection netiyatharin...       2  
54  vayasilum ingane maargam kalikkaan laalettane ...       2  
55  Trailer evidakkayo katha muyavanayum kanikkunn...       0  
56           Ee pennungalkku kannu kaanaanille Shava൦       1  
57  Jojoyute chettante abhinayao athu oru athbhuda...       2  
58  Oru katta mammookka phaan aaya njaan mukkutthi...       2  
59                      Promo kand kili poya le njaan       4  
60  Ith kidukkum Ellarum abhinayikkunath pole feel...       2  
61  Allelum tcr besu cheythu patam irakkiyo athu g...       2  
62                                         Thalaivaaa       3  
63  Mattannaal varunna teaser nu ippozhe katta wai...       2  
64  Karikkile lolante premam kandittundo onnu kand...       4  
65  Aa urumi karakki adikkunnathu woe romangification       2  
66  Trailer video polum puratthu varunnathinu munn...       1  
67  Nammute ikka ee praavashyam varunnathu boksu‌ ...       2  
68  Lucifer film kandittu trailer kanunevar ethra ...       4  
69  Nylaykku pattuvo Thumpiye kondu kallu etuppiyk...       0

In [42]:
Test_Data

id                                              text1  \
0        Mal_1  Teaserinu kurach samayamkoodi mathram. Cant wa...   
1        Mal_2              Appol kathayute  roottu maariyallo...   
2        Mal_3  Mootthon tryler trending list varaatthathu ent...   
3        Mal_4  Nowadays 944k views is considered as 1m views ...   
4        Mal_5  Maass.Trailer ennu paranja ithaanu makkale.......   
...        ...                                                ...   
1957  Mal_1958  Expression vacchu nokkumpol mookkutthi kattath...   
1958  Mal_1959                       Enikku oru  100 like tharumo   
1959  Mal_1960  Nannayi onnu poliyunna lakshnm unde...Thrill m...   
1960  Mal_1961  Athikam eduthu kayatti vekkenda....Direction k...   
1961  Mal_1962  Ithupole mooonchiya oru padam jeevithathil kan...   

                                  Msg_without_Stopwords  
0       Teaserinu kurach samayamkoodi mathram Cant wait  
1                     Appol kathayute roottu maariyallo  
2     Mootthon tryler trending list varaatthathu enthaa  
3              Nowadays k views considered views kerala  
4     MaassTrailer ennu paranja ithaanu makkaleKatta...  
...                                                 ...  
1957  Expression vacchu nokkumpol mookkutthi kattath...  
1958                            Enikku oru like tharumo  
1959  Nannayi onnu poliyunna lakshnm undeThrill main...  
1960  Athikam eduthu kayatti vekkendaDirection kke k...  
1961  Ithupole mooonchiya oru padam jeevithathil kan...  

[1962 rows x 3 columns]

In [43]:
X_train=Train_Data['Msg_without_Stopwords']
y_train=Train_Data['Nlabel']

X_Dev=Dev_Data['Msg_without_Stopwords']
y_Dev=Dev_Data['Nlabel']

X_test=Test_Data['Msg_without_Stopwords']

In [44]:
X_train.shape, y_train.shape, X_Dev.shape, y_Dev.shape, X_test.shape

((15888,), (15888,), (1766,), (1766,), (1962,))

Not_offensive                           14153     0
not-malayalam                            1287     4
Offensive_Targeted_Insult_Individual      239     2
Offensive_Untargetede                     191     3
Offensive_Targeted_Insult_Group           140     1


Not_offensive                           1779      0
not-malayalam                            163      4
Offensive_Targeted_Insult_Individual      24      2
Offensive_Untargetede                     20      3
Offensive_Targeted_Insult_Group           13      1

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True , ngram_range=(1, 1))
X=tfidf.fit_transform(X_train) 
Y=y_train
tfidf

TfidfVectorizer()

In [46]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(5, 5))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', ngram_range=(5, 5))

In [47]:
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())


(39913, 118332, 39913, 118332)

In [48]:
tfidf.vocabulary_

{'sunny': 33291,
 'chechi': 5742,
 'fans': 9697,
 'evide': 9478,
 'like': 18519,
 'adichu': 1702,
 'power': 28869,
 'kaniku': 14937,
 'angane': 2666,
 'july': 13258,
 'month': 21387,
 'ile': 11147,
 'ende': 8268,
 'aadyathe': 122,
 'leave': 18416,
 'njan': 23840,
 'angu': 2716,
 'edukuva': 7905,
 'nu': 24263,
 'ettante': 9281,
 'puthiya': 29917,
 'patatthinu': 26576,
 'vendi': 38278,
 'kaatthirikkunnavar': 13849,
 'lyk': 18785,
 'battan': 4576,
 'aticchu': 3751,
 'polikko': 28161,
 'ini': 11548,
 'laalettante': 18135,
 'vetta': 38507,
 'thutangaan': 35440,
 'pokunnu': 27953,
 'mun': 21931,
 'kaala': 13315,
 'collection': 6855,
 'recordukal': 30588,
 'bhethicchirikkum': 4876,
 'trailer': 35648,
 'powli': 28877,
 'oru': 25029,
 'raksha': 30338,
 'illa': 11154,
 'pakshea': 25803,
 'padam': 25528,
 'irangattea': 11791,
 'veruthea': 38447,
 'degrade': 7249,
 'venda': 38245,
 'irangittu': 11804,
 'paraya': 26192,
 'malayalam': 19546,
 'thanne': 34192,
 'aanu': 594,
 'vere': 38347,
 'level': 

In [49]:
char_tfidf.vocabulary_

{'sunny': 97729,
 'unny ': 107980,
 'nny c': 76749,
 'ny ch': 78666,
 'y che': 112796,
 ' chec': 1746,
 'chech': 25618,
 'hechi': 43232,
 'echi ': 32604,
 'chi f': 25721,
 'hi fa': 43856,
 'i fan': 46880,
 ' fans': 2788,
 'fans ': 38520,
 'ans e': 18861,
 'ns ev': 77287,
 's evi': 94132,
 ' evid': 2714,
 'evide': 37745,
 'vide ': 111061,
 'ide l': 48328,
 'de li': 28057,
 'e lik': 31310,
 ' like': 4595,
 'like ': 63134,
 'ike a': 49431,
 'ke ad': 56840,
 'e adi': 30574,
 ' adic': 607,
 'adich': 13679,
 'dichu': 29017,
 'ichu ': 48137,
 'chu p': 25916,
 'hu po': 45806,
 'u pow': 104788,
 ' powe': 6392,
 'power': 87204,
 'ower ': 84746,
 'wer k': 112198,
 'er ka': 36055,
 'r kan': 88602,
 ' kani': 3980,
 'kanik': 56466,
 'aniku': 18410,
 'angan': 18285,
 'ngane': 74532,
 'gane ': 39840,
 'ane j': 18165,
 'ne ju': 73670,
 'e jul': 31176,
 ' july': 3834,
 'july ': 55233,
 'uly m': 106807,
 'ly mo': 65672,
 'y mon': 112994,
 ' mont': 5021,
 'month': 69833,
 'onth ': 82258,
 'nth i': 77757,


In [50]:
X, X_char

(<15888x39913 sparse matrix of type '<class 'numpy.float64'>'
 	with 146448 stored elements in Compressed Sparse Row format>,
 <15888x118332 sparse matrix of type '<class 'numpy.float64'>'
 	with 1086990 stored elements in Compressed Sparse Row format>)

In [51]:
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<15888x158245 sparse matrix of type '<class 'numpy.float64'>'
	with 1233438 stored elements in COOrdinate format>

In [52]:
Xt=tfidf.transform(X_Dev) 
Xt_char=char_tfidf.transform(X_Dev)

In [53]:
Xt, Xt_char

(<1766x39913 sparse matrix of type '<class 'numpy.float64'>'
 	with 13041 stored elements in Compressed Sparse Row format>,
 <1766x118332 sparse matrix of type '<class 'numpy.float64'>'
 	with 114362 stored elements in Compressed Sparse Row format>)

In [54]:
Dev=hstack([Xt,Xt_char])
Dev

<1766x158245 sparse matrix of type '<class 'numpy.float64'>'
	with 127403 stored elements in COOrdinate format>

In [55]:
test_Mal_Hasoc_word=tfidf.transform(X_test)
test_Mal_Hasoc_char=char_tfidf.transform(X_test)
test_Mal_Hasoc_word_char=hstack([test_Mal_Hasoc_word,test_Mal_Hasoc_char])

In [56]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, f1_score

e:\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [57]:
def trainer(model_obj, param, X, X_char, train, Xt, Xt_char, Dev, Y, y_Dev):
   
    model_obj.fit(X,Y)
#Training Classifier with TF-IDF Features Word n-gram
    print("Accuracy of Word n-gram(1,2) :", (model_obj.score(Xt, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Xt)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=model_obj.predict(test_Mal_Hasoc_word)
    
    pre=precision_score(y_Dev, predict, average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

#Training Classifier with TF-IDF Features Char n-gram
    model_obj.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,5) :", (model_obj.score(Xt_char, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Xt_char)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=model_obj.predict(test_Mal_Hasoc_char)
    
    pre=precision_score(y_Dev, predict, average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)
        
              
#Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    model_obj.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (model_obj.score(Dev, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Dev)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=model_obj.predict(test_Mal_Hasoc_word_char)
    
    pre=precision_score(y_Dev, predict,  average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre,)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

    
    return word, char, word_char

In [58]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
trainer(MNB,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)
#w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)
# w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,2) : 0.587202718006795
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       1.00      0.03      0.07       237
           2       0.54      0.95      0.69       706
           3       1.00      0.02      0.04       141
           4       0.70      0.61      0.65       580

    accuracy                           0.59      1766
   macro avg       0.65      0.32      0.29      1766
weighted avg       0.66      0.59      0.50      1766

Confusion Matrix
[[  0   0  80   0  22]
 [  0   8 165   0  64]
 [  0   0 674   0  32]
 [  0   0 103   3  35]
 [  0   0 228   0 352]]
 
Precision :  0.587202718006795
Recall :  0.587202718006795
F1 Score :  0.587202718006795
Accuracy of Char n-gram(1,5) : 0.5906002265005662
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       1.00      0.02      0.03       237
     

e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(array([4, 2, 2, ..., 2, 2, 2]),
 array([2, 2, 2, ..., 2, 2, 2]),
 array([4, 2, 2, ..., 2, 2, 2]))

In [59]:
#from sklearn.tree import DecisionTreeClassifier

#DTC=DecisionTreeClassifier()
#trainer(DTC,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)

In [60]:
from imblearn.over_sampling import SMOTE

In [61]:
smote = SMOTE()

In [62]:
x_smote_Word, y_smote_Word = smote.fit_resample(X, Y)
x_smote_Char, y_smote_Char = smote.fit_resample(X_char, Y)
x_smote_Comb, y_smote_Comb = smote.fit_resample(train, Y)

In [63]:
Y.value_counts()

2    6421
4    5279
1    2105
3    1157
0     926
Name: Nlabel, dtype: int64

In [64]:
x_smote_Word.shape, y_smote_Word.shape, x_smote_Char.shape, y_smote_Char.shape, x_smote_Comb.shape, y_smote_Comb.shape

((32105, 39913),
 (32105,),
 (32105, 118332),
 (32105,),
 (32105, 158245),
 (32105,))

In [65]:
# Development Dataset
x_smote_Word_Dev, y_smote_Word_Dev = smote.fit_resample(Xt, y_Dev)
x_smote_Char_Dev, y_smote_Char_Dev = smote.fit_resample(Xt_char, y_Dev)
x_smote_Comb_Dev, y_smote_Comb_Dev = smote.fit_resample(Dev, y_Dev)

In [66]:
x_smote_Word_Dev.shape, y_smote_Word_Dev.shape, x_smote_Char_Dev.shape, y_smote_Char_Dev.shape, x_smote_Comb_Dev.shape, y_smote_Comb_Dev.shape

((3530, 39913), (3530,), (3530, 118332), (3530,), (3530, 158245), (3530,))

In [67]:
from sklearn.model_selection import GridSearchCV


In [68]:
def trainer1111(model_obj, param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev):
    # Training Classifier  with TF-IDF Features Word n-gram(1,2)
    GSCV=GridSearchCV(model_obj, param , cv=10,return_train_score=False)
    GSCV.fit(x_smote_Word, y_smote_Word)
    print("Accuracy of Word n-gram(1,1) :", (GSCV.score(x_smote_Word_Dev, y_smote_Word_Dev)))
    #Printing Classification Report
    predict=GSCV.predict(x_smote_Word_Dev)
    print(classification_report(y_smote_Word_Dev, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Word_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Mal_Hasoc_word)
 
    accuracy = accuracy_score(y_smote_Word_Dev, predict)
    recall = recall_score(y_smote_Word_Dev, predict, average='weighted')
    precision = precision_score(y_smote_Word_Dev, predict, average='weighted')
    f1score = f1_score(y_smote_Word_Dev, predict, average='weighted')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    
    #Training Classifier with TF-IDF Features Char n-gram(1,5)
    GSCV.fit(x_smote_Char, y_smote_Char)
    print("Accuracy of Char n-gram(1,5) :", (GSCV.score(x_smote_Char_Dev, y_smote_Char_Dev)))
    predict=GSCV.predict(x_smote_Char_Dev)
    print(classification_report(y_smote_Char_Dev, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Char_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Mal_Hasoc_char)
    
    accuracy = accuracy_score(y_smote_Char_Dev, predict)
    recall = recall_score(y_smote_Char_Dev, predict, average='weighted')
    precision = precision_score(y_smote_Char_Dev, predict, average='weighted')
    f1score = f1_score(y_smote_Char_Dev, predict, average='weighted')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    
   
    
    
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(x_smote_Comb, y_smote_Comb)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(x_smote_Comb, y_smote_Comb)))
    #Printing Classification Report
    predict=GSCV.predict(x_smote_Comb_Dev)
    print(classification_report(y_smote_Comb_Dev, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Comb_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Mal_Hasoc_word_char)
    
    accuracy = accuracy_score(y_smote_Comb_Dev, predict)
    recall = recall_score(y_smote_Comb_Dev, predict, average='weighted')
    precision = precision_score(y_smote_Comb_Dev, predict, average='weighted')
    f1score = f1_score(y_smote_Comb_Dev, predict, average='weighted')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    return word, char, word_char

In [69]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
param={'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 'multi_class':('ovr', 'auto')}
print("Multi Nominal Bayes")
#trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)
w_mnb,c_mnb,wc_mnb=trainer1111(LR,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

Multi Nominal Bayes


e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

Accuracy of Word n-gram(1,1) : 0.7104815864022663
              precision    recall  f1-score   support

           0       0.78      0.58      0.66       706
           1       0.76      0.62      0.68       706
           2       0.60      0.75      0.67       706
           3       0.81      0.93      0.87       706
           4       0.65      0.67      0.66       706

    accuracy                           0.71      3530
   macro avg       0.72      0.71      0.71      3530
weighted avg       0.72      0.71      0.71      3530

Best Parameters  {'multi_class': 'auto', 'solver': 'newton-cg'}
Best Score  0.8577502665583939
 
Confusion Matrix
[[407  59 145  29  66]
 [ 47 440  89  24 106]
 [ 35  32 530  38  71]
 [  7   0  31 660   8]
 [ 27  51  91  66 471]]
 
accuracy: 0.7104815864022663, recall: 0.7104815864022663, precision: 0.718519732292608, f1-score: 0.707552072012003


e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

Accuracy of Char n-gram(1,5) : 0.7535410764872521
              precision    recall  f1-score   support

           0       0.80      0.65      0.72       706
           1       0.72      0.68      0.70       706
           2       0.66      0.77      0.71       706
           3       0.91      0.96      0.94       706
           4       0.69      0.71      0.70       706

    accuracy                           0.75      3530
   macro avg       0.76      0.75      0.75      3530
weighted avg       0.76      0.75      0.75      3530

Best Parameters  {'multi_class': 'auto', 'solver': 'lbfgs'}
Best Score  0.8559727610792729
 
Confusion Matrix
[[457  65 127   3  54]
 [ 59 482  65   9  91]
 [ 32  35 544  29  66]
 [  0   3  13 678  12]
 [ 23  84  75  25 499]]
 
accuracy: 0.7535410764872521, recall: 0.7535410764872521, precision: 0.7566897639932927, f1-score: 0.7523988002955119


e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

Accuracy of Combinining word & Char n-gram 0.975517832113378
              precision    recall  f1-score   support

           0       0.83      0.60      0.70       706
           1       0.84      0.65      0.73       706
           2       0.60      0.82      0.70       706
           3       0.91      0.93      0.92       706
           4       0.67      0.74      0.70       706

    accuracy                           0.75      3530
   macro avg       0.77      0.75      0.75      3530
weighted avg       0.77      0.75      0.75      3530

Best Parameters  {'multi_class': 'auto', 'solver': 'newton-cg'}
Best Score  0.8998003552818339
 
Confusion Matrix
[[427  27 157   9  86]
 [ 39 459 107   5  96]
 [ 23  16 582  20  65]
 [  1   2  32 655  16]
 [ 24  43  87  29 523]]
 
accuracy: 0.7495750708215297, recall: 0.7495750708215297, precision: 0.7701242527269986, f1-score: 0.7500493470480832


In [73]:
from sklearn.naive_bayes import MultinomialNB
MNB11=MultinomialNB()
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
#trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)
w_mnb,c_mnb,wc_mnb=trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

Multi Nominal Bayes
Accuracy of Word n-gram(1,1) : 0.7286118980169972
              precision    recall  f1-score   support

           0       0.70      0.64      0.67       706
           1       0.70      0.72      0.71       706
           2       0.65      0.75      0.70       706
           3       0.89      0.93      0.91       706
           4       0.70      0.60      0.65       706

    accuracy                           0.73      3530
   macro avg       0.73      0.73      0.73      3530
weighted avg       0.73      0.73      0.73      3530

Best Parameters  {'alpha': 0.5}
Best Score  0.8622975441701083
 
Confusion Matrix
[[451  89 108   0  58]
 [ 68 511  55   9  63]
 [ 56  42 529  30  49]
 [ 16   3  23 656   8]
 [ 57  87  94  43 425]]
 
accuracy: 0.7286118980169972, recall: 0.7286118980169972, precision: 0.728333391544719, f1-score: 0.726634271764995
Accuracy of Char n-gram(1,5) : 0.753257790368272
              precision    recall  f1-score   support

           0       0.

In [417]:
wc_mnb

array([4, 2, 2, ..., 1, 2, 1])

In [419]:
wc_mnb=pd.DataFrame(wc_mnb, columns=["Word_MNB"])
FINAL=pd.concat([X_test, wc_mnb], axis=1)
FINAL=FINAL.rename(columns={"Msg_without_Stopwords": "text", "Word_MNB": "label"})

FINAL['label'] = FINAL['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-malayalam', 4 : 'unknown_state'})
FINAL

text          label
0       Teaserinu kurach samayamkoodi mathram Cant wait  unknown_state
1                     Appol kathayute roottu maariyallo       Positive
2     Mootthon tryler trending list varaatthathu enthaa       Positive
3              Nowadays k views considered views kerala  not-malayalam
4     MaassTrailer ennu paranja ithaanu makkaleKatta...       Positive
...                                                 ...            ...
1957  Expression vacchu nokkumpol mookkutthi kattath...  unknown_state
1958                            Enikku oru like tharumo  unknown_state
1959  Nannayi onnu poliyunna lakshnm undeThrill main...       Negative
1960  Athikam eduthu kayatti vekkendaDirection kke k...       Positive
1961  Ithupole mooonchiya oru padam jeevithathil kan...       Negative

[1962 rows x 2 columns]

In [420]:
FINAL.to_csv("MNB_Malayalam_HASOC21.tsv")

In [74]:
from sklearn.naive_bayes import MultinomialNB
DTC1=DecisionTreeClassifier()
param={'criterion':('gini', 'entropy')}
print("Multi Nominal Bayes")
#trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)
w_mnb,c_mnb,wc_mnb=trainer1111(DTC1,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

Multi Nominal Bayes
Accuracy of Word n-gram(1,1) : 0.5399433427762039
              precision    recall  f1-score   support

           0       0.66      0.31      0.42       706
           1       0.61      0.47      0.53       706
           2       0.39      0.64      0.49       706
           3       0.71      0.75      0.73       706
           4       0.49      0.53      0.51       706

    accuracy                           0.54      3530
   macro avg       0.57      0.54      0.54      3530
weighted avg       0.57      0.54      0.54      3530

Best Parameters  {'criterion': 'gini'}
Best Score  0.7428796262070316
 
Confusion Matrix
[[220  98 246  49  93]
 [ 58 330 153  40 125]
 [ 30  51 454  57 114]
 [  3  11 109 530  53]
 [ 23  51 191  69 372]]
 
accuracy: 0.5399433427762039, recall: 0.5399433427762039, precision: 0.5399433427762039, f1-score: 0.5399433427762039
Accuracy of Char n-gram(1,5) : 0.38470254957507083
              precision    recall  f1-score   support

          

# Positive          6421 2
unknown_state     5279 4
Negative          2105 1
not-malayalam     1157 3
Mixed_feelings     926 0

In [118]:
FINAL.to_csv("MNB_Malayalam_HASOC21.tsv")

In [74]:
from sklearn.ensemble import RandomForestClassifier
RFC11=RandomForestClassifier()
param={'n_estimators': [50, 100, 200, 400]}
print("RFC")0.
w_mnb,c_mnb,wc_mnb=trainer1111(RFC11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

RFC


KeyboardInterrupt: 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC11=RandomForestClassifier()
param={'n_estimators': [200, 400, 600, 800, 1000, 1200]}
print("RFC")
#param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_mnb,c_mnb,wc_mnb=trainer1111(RFC11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

RFC


In [1]:
pip install inltk

Note: you may need to restart the kernel to use updated packages.


In [2]:
from inltk.inltk import setup
setup('hi')

In [1]:
pip install indic-nlp-library

Note: you may need to restart the kernel to use updated packages.


In [14]:
from indicnlp.transliterate.unicode_transliterate import UnicodeIndicTransliterator

# Input text "Today the weather is good. Sun is bright and there are no signs of rain. Hence we can play today."
input_text='ente mammookka ningal puliyalla oru simhama'

# Transliterate from Hindi to Telugu
print(UnicodeIndicTransliterator.transliterate(input_text,"en","ml"))

ente mammookka ningal puliyalla oru simhama


In [18]:
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator

input_text=u'आज मौसम अच्छा है। इसलिए हम आज खेल सकते हैं!'

# Transliterate Hindi to Roman
print(ItransTransliterator.to_itrans(input_text, 'ta'))

आज मौसम अच्छा है। इसलिए हम आज खेल सकते हैं!


In [20]:
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator

input_text = u'ஒன்றுமட்டுமல்லாது'
lang='ta'
input_text = ItransTransliterator.to_itrans(input_text,lang)
print(input_text)
#OUTPUT : .oऩRumaTTumallAtu

from indicnlp.transliterate.unicode_transliterate import ItransTransliterator
lang='ta'
x=ItransTransliterator.from_itrans(input_text,lang)
print(x) 
#OUTPUT :  ஒனறுமட்டுமல்லாது

ஒுமுமாு
ஒுமுமாு
