In [1]:
from sklearn.datasets import load_files
import pandas as pd

In [2]:
#Malayalam
Mal_train=pd.read_csv("kannada_sentiment_full_train.tsv", sep='\t')


Mal_Dev=pd.read_csv("kannada_sentiment_full_dev.tsv", sep='\t')


Mal_test=pd.read_csv("kannada_sentiment_full_test_withoutlabels.tsv", sep='\t')

In [3]:
Mal_train.shape, Mal_Dev.shape, Mal_test.shape

((6212, 2), (691, 2), (768, 2))

In [4]:
Mal_test.head()

id                                               text
0  Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1  Kan_2                                         Jai D Boss
2  Kan_3                                     Signature move
3  Kan_4                                     Super song bro
4  Kan_5                        Wow  Super agi helidira sir

In [5]:
#import googletrans
#from googletrans import Translator

In [6]:
#translator = Translator()

In [7]:
#print(googletrans.LANGUAGES)

In [8]:
#Mal_train['text1'] = Mal_train['text'].apply(translator.translate, src='kn', dest='en').apply(getattr, args=('text',))
#Mal_train

In [9]:
#translated = translator.translate('ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ')
#print(translated)
#translated.text


In [10]:
#Mal_train.text

In [11]:
#translations = {}
#for column in Mal_train.text:
    # unique elements of the column
  #  unique_elements = Mal_train[column].unique()
  #  for element in unique_elements:
        # add translation to the dictionary
   #     translations[element] = translator.translate(element).text
    
#print(translations)

In [12]:
#translations = {}
#for column in df_en.columns:
    # unique elements of the column
   # unique_elements = df_en[column].unique()
   # for element in unique_elements:
        # add translation to the dictionary
    #    translations[element] = translator.translate(element).text
    
#print(translations)

In [13]:
#converter = ml2en()

#desti_lang={
 #    'malayalam' : 'ml'
#}

In [14]:
#for key,value in desti_lang.items():
     #print(transt.translate(Mal_train['text']))
     #   Mal_train['text1']=Mal_train['text'].apply(lambda x: converter.transliterate(x))
     #   Mal_Dev['text1']=Mal_Dev['text'].apply(lambda x: converter.transliterate(x))
      #  Mal_test['text1']=Mal_test['text'].apply(lambda x: converter.transliterate(x))

In [15]:
Mal_train[61:70]

text     category
61                               SupernTelugu lo kuda     Positive
62                          Rakshit shetty sir ge jai     Positive
63                   different but unique & epic song  not-Kannada
64                        Even I had Same feelings..!  not-Kannada
65  First time movie nodoru taleli uoohe screenply...     Positive
66                         Super................ Song  not-Kannada
67                           Good job..  Goahead mahn  not-Kannada
68  En song guruve I love this song K G F bitre ed...     Positive
69  Nimage aa devaru olledu madali Appaji...nNimma...     Positive

In [16]:
Mal_Dev.head()

text        category
0  Binduge saryagi ugithidira good go ahead  we a...  Mixed feelings
1                             yen song guru ...super        Positive
2                                   my fevorat story     not-Kannada
3                                  Super ತೋಗರಿ ತೀಪ್ಪ        Positive
4  ನಿಮ್ಮ ಮಾತುಗಳು ಅಕ್ಷರಶಃ ಸತ್ಯ... ನಿಮ್ಮ ಈ ಸಾಮಾನ್ಯ ...        Positive

In [17]:
Mal_test.head()

id                                               text
0  Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1  Kan_2                                         Jai D Boss
2  Kan_3                                     Signature move
3  Kan_4                                     Super song bro
4  Kan_5                        Wow  Super agi helidira sir

In [18]:
# Train
Mal_train['category'].value_counts()

Positive          2823
Negative          1188
not-Kannada        916
unknown state      711
Mixed feelings     574
Name: category, dtype: int64

In [19]:
# Development 
Mal_Dev['category'].value_counts()

Positive          321
Negative          139
not-Kannada       110
unknown state      69
Mixed feelings     52
Name: category, dtype: int64

In [20]:
msg=Mal_train['text']

msgDev=Mal_Dev['text']

msgTest=Mal_test['text']

In [21]:
msgDev[50:70]

50    Guru ninge like beku andre kelu Kodthare adu b...
51                      super comedy drama togari tippa
52                                    @Deekshit Chandra
53    Enadru public help ago Vishayada bagge Mathadi...
54                        Nammantavrge spoorti nivu sir
55             Estu kelidru matte matte kelbeku ansutte
56                           Pakka 100 days movie  edu.
57                              Nice story togari tippa
58         ಶಂಕರ್ ಅಶ್ವಥ್ ರೊಂದಿಗೆ ಅತ್ಯಂತ ಸುಂದರವಾದ ಸಂದರ್ಶನ
59                                    Plz make in Hindi
60                                      Sooperb concept
61             Navu kuri Alla guru kaliyugada kaligallu
62                      Ye movie hindi mein hogi k nahi
63         Please innodh video maadi bro ticktock bagge
64       Nodarappa yaro heludrala ban yak madbeku antha
65                           super.nTogari Tippa Comody
66                ಏ... ಭೈ ಏನೋಪ ನೀ ಹಿಂಗ ಮೈ ತೊಳೆದು ಬಿಟ್ಟಿ
67    Kolthogiro kobri mitai mukadavle na..?nYap

In [22]:
#Remove Emojis

def emoji(msg): 
    
    msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
    
    msg_digit=msg_emoj.str.replace(r'[0-9]', ' ')

    msg_Spac = msg_digit.str.replace(r'_',' ')

    msg_Spac = msg_Spac.str.replace(r'.','')

    msg_Spac = msg_Spac.str.replace(r'!','')

    msg_Spac = msg_Spac.str.replace(r'#','')

    msg_Spac = msg_Spac.str.replace(r'%','')

    msg_Spac = msg_Spac.str.replace(r'&','')

    msg_Spac = msg_Spac.str.replace(r'’','')

    msg_Spac = msg_Spac.str.replace(r'(','')

    msg_Spac = msg_Spac.str.replace(r')','')

    msg_Spac = msg_Spac.str.replace(r'-','')

    msg_Spac = msg_Spac.str.replace(r'/','')

    msg_Spac = msg_Spac.str.replace(r':','')

    msg_Spac = msg_Spac.str.replace(r';','')

    msg_Spac = msg_Spac.str.replace(r'<','')

    msg_Spac = msg_Spac.str.replace(r'=','')

    msg_Spac = msg_Spac.str.replace(r'>','')

    msg_Spac = msg_Spac.str.replace(r'?','')

    msg_Spac = msg_Spac.str.replace(r'@','')

    msg_Spac = msg_Spac.str.replace(r'[','')

    msg_Spac = msg_Spac.str.replace(r']','')

    msg_Spac = msg_Spac.str.replace(r'^','')

    msg_Spac = msg_Spac.str.replace(r'{','')

    msg_Spac = msg_Spac.str.replace(r'}','')

    msg_Spac = msg_Spac.str.replace(r'|','')

    msg_Spac = msg_Spac.str.replace(r'~','')

    msg_Spac = msg_Spac.str.replace(r'+','')

    msg_Spac = msg_Spac.str.replace(r'\s+', ' ')


    return msg_Spac
    

In [23]:
msg_Train=emoji(msg)

msg_Dev=emoji(msgDev)

msg_Test=emoji(msgTest)

e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: The default value of regex will c

In [24]:
msg_Test.head()

0    ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1                                           Jai D Boss
2                                       Signature move
3                                       Super song bro
4                           Wow Super agi helidira sir
Name: text, dtype: object

In [25]:
msg_Train[78:90], msg_Dev[50:70], msg_Test[21:22]


(78                                           Hi Chi ugh
 79                nivu helidu sari nanu follow madthini
 80    Sir paisacom adara bagge video madi Open madod...
 81    Entha song na dislike madtiralla loafer nan ma...
 82                           Pubg kooda ban agbeku guru
 83                                  Manju Sonu ಅಭಿನಂದನೆ
 84                             That making was osm ASN 
 85                   ಈ ಹಾಡು ರಶ್ಮಿಕ ಮಂಗಣ್ಣನವರಿಗೆ ಅರ್ಪಣೆ 
 86                             Super guru awesome video
 87    Nandi Parthasarathi ಓಹೋ ನಂದಿನಿ ನಿಂದು ಮಿಲ್ಕ್ ಪಾ...
 88           prithvi nayak Roberrt bangada goth aagutte
 89                                One like for hands up
 Name: text, dtype: object,
 50    Guru ninge like beku andre kelu Kodthare adu b...
 51                      super comedy drama togari tippa
 52                                     Deekshit Chandra
 53    Enadru public help ago Vishayada bagge Mathadi...
 54                        Nammantavrge spoorti nivu sir
 55

In [26]:
Train_Df=pd.DataFrame(msg_Train)
Train_Df.columns=['Msg_with_Stopwords']

Dev_Df=pd.DataFrame(msg_Dev)
Dev_Df.columns=['Msg_with_Stopwords']

Test_Df=pd.DataFrame(msg_Test)
Test_Df.columns=['Msg_with_Stopwords']

In [27]:
Train_Df.shape, Dev_Df.shape, Test_Df.shape

((6212, 1), (691, 1), (768, 1))

In [28]:
# Removing Null Values

Train_Df['Msg_with_Stopwords']=Train_Df['Msg_with_Stopwords'].fillna("")

Dev_Df['Msg_with_Stopwords']=Dev_Df['Msg_with_Stopwords'].fillna("")

Test_Df['Msg_with_Stopwords']=Test_Df['Msg_with_Stopwords'].fillna("")


In [29]:
Mal_train.shape, Mal_Dev.shape,Train_Df.shape, Dev_Df.shape, Mal_test.shape, Test_Df.shape

((6212, 2), (691, 2), (6212, 1), (691, 1), (768, 2), (768, 1))

In [30]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [31]:
stop_words = set(stopwords.words('english'))

In [32]:
Train_Df['Msg_without_Stopwords']=Train_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Dev_Df['Msg_without_Stopwords']=Dev_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Test_Df['Msg_without_Stopwords']=Test_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [33]:
Train_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_with_Stopwords'].tolist()]
Train_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_without_Stopwords'].tolist()]

Dev_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_with_Stopwords'].tolist()]
Dev_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_without_Stopwords'].tolist()]

Test_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_with_Stopwords'].tolist()]
Test_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_without_Stopwords'].tolist()]

In [34]:
Train_Data=pd.concat([Mal_train, Train_Df], axis=1)

Dev_Data=pd.concat([Mal_Dev, Dev_Df], axis=1)

Test_Data=pd.concat([Mal_test, Test_Df], axis=1)

In [35]:
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((6212, 6), (691, 6), (768, 6))

In [36]:
Test_Data

id                                               text  \
0      Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...   
1      Kan_2                                         Jai D Boss   
2      Kan_3                                     Signature move   
3      Kan_4                                     Super song bro   
4      Kan_5                        Wow  Super agi helidira sir   
..       ...                                                ...   
763  Kan_764                                Thu thukali trailer   
764  Kan_765  Siri gannadam galge haakbitallapa Thu  yaro ni...   
765  Kan_766  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...   
766  Kan_767  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲ.nದಯವಿ...   
767  Kan_768  magaluru kade kalsi avanannu .navu avanige mad...   

                                    Msg_with_Stopwords  \
0    ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...   
1                                           Jai D Boss   
2                                       Signature move   
3                                       Super song bro   
4                           Wow Super agi helidira sir   
..                                                 ...   
763                                Thu thukali trailer   
764  Siri gannadam galge haakbitallapa Thu yaro nin...   
765  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...   
766  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲnದಯವಿಟ...   
767  magaluru kade kalsi avanannu navu avanige madd...   

                                 Msg_without_Stopwords  \
0    ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...   
1                                           Jai D Boss   
2                                       Signature move   
3                                       Super song bro   
4                           Wow Super agi helidira sir   
..                                                 ...   
763                                Thu thukali trailer   
764  Siri gannadam galge haakbitallapa Thu yaro nin...   
765  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...   
766  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲnದಯವಿಟ...   
767  magaluru kade kalsi avanannu navu avanige madd...   

     Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  
0                        14                         14  
1                         3                          3  
2                         2                          2  
3                         3                          3  
4                         5                          5  
..                      ...                        ...  
763                       3                          3  
764                      11                         11  
765                      11                         11  
766                       7                          7  
767                       8                          8  

[768 rows x 6 columns]

In [37]:
Train_Data=Train_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Dev_Data=Dev_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Test_Data=Test_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)


In [38]:
# Dataset Train & Dev are : (1) Message_Without_Stopwords and (2) labels
# Only Test is : (1) Message_Without_Stopwords
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((6212, 2), (691, 2), (768, 2))

In [39]:
Train_Data

category                              Msg_without_Stopwords
0           Negative  ಒಂದು ದೇಶದ ಮುಂದುವರಿಯುವುದು ಅದರ ಆರ್ಥಿಕ ಸ್ಥಿತಿಯನ್ನ...
1           Positive  ಕನ್ನಡದಲ್ಲಿ ಡೈಲಿ ಟೆಕ್ ಅಪ್ಡೇಟ್ಸ್ ಪಡೆಯಲು ಸಬ್ಸ್ಕ್ರ...
2        not-Kannada                                     Super sar song
3           Negative  Tiktokers present situation nನೋಡುವವರು ಯಾರು ನಮ್...
4           Positive                              Super ಸಾಂಗ್ ವೆರಿ ನೈಸ್
...              ...                                                ...
6207     not-Kannada  ARW tumbad tanhaji andhadhun aise bahot hai pr...
6208     not-Kannada                   പൊളി ഡാൻസ് രക്ഷിത് ഷെട്ടി മാസ്സ്
6209        Negative  BronNeen este Roast madudruChina ne beku antha...
6210        Positive  ಕೌಶಲ್ಯ ಇದ್ದವರ ಸಂಖ್ಯೆ ಕಡಿಮೆ ಇಲ್ಲ ಸರ್ ತುಂಬಾ ಪ್ರತ...
6211  Mixed feelings                                            M Views

[6212 rows x 2 columns]

In [40]:
Dev_Data

category                              Msg_without_Stopwords
0    Mixed feelings  Binduge saryagi ugithidira good go ahead enjoy...
1          Positive                                yen song guru super
2       not-Kannada                                      fevorat story
3          Positive                                  Super ತೋಗರಿ ತೀಪ್ಪ
4          Positive  ನಿಮ್ಮ ಮಾತುಗಳು ಅಕ್ಷರಶಃ ಸತ್ಯ ನಿಮ್ಮ ಈ ಸಾಮಾನ್ಯ ಜೀವ...
..              ...                                                ...
686        Negative   Nandi Parthasarathi ನಿಮ್ಮ ಅಪ್ಪ ದೊಡ್ ಗಾಂಡು ಸೂಳೆಮಗ
687        Negative                               Hugi guru badethawke
688        Positive                                       Trending wow
689        Positive  Troll Stupid Fans naanu adikke kano helthirodu...
690        Positive  JustAn Opinion ninu Tika mucchuEvattu Kannada ...

[691 rows x 2 columns]

In [41]:
Test_Data

id                              Msg_without_Stopwords
0      Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1      Kan_2                                         Jai D Boss
2      Kan_3                                     Signature move
3      Kan_4                                     Super song bro
4      Kan_5                         Wow Super agi helidira sir
..       ...                                                ...
763  Kan_764                                Thu thukali trailer
764  Kan_765  Siri gannadam galge haakbitallapa Thu yaro nin...
765  Kan_766  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...
766  Kan_767  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲnದಯವಿಟ...
767  Kan_768  magaluru kade kalsi avanannu navu avanige madd...

[768 rows x 2 columns]

In [42]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 

In [43]:
Train_Data['Nlabel'].value_counts()

2    2823
1    1188
3     916
4     711
0     574
Name: Nlabel, dtype: int64

In [44]:
2    2823
1    1188
3     916
4     711
0     574

Positive   2       2823
Negative   1       1188
not-Kannada  3      916
unknown state 4     711
Mixed feelings  0   574

Positive          6421 2
unknown_state     5279 4
Negative          2105 1
not-malayalam     1157 3
Mixed_feelings     926 0

Positive          706 2
unknown_state     580 4
Negative          237 1
not-malayalam     141 3
Mixed_feelings    102 0

SyntaxError: invalid syntax (<ipython-input-44-56fc72ccd4e7>, line 1)

In [44]:
Dev_Data['Nlabel'].value_counts()

2    321
1    139
3    110
4     69
0     52
Name: Nlabel, dtype: int64

In [45]:
Train_Data

category                              Msg_without_Stopwords  \
0           Negative  ಒಂದು ದೇಶದ ಮುಂದುವರಿಯುವುದು ಅದರ ಆರ್ಥಿಕ ಸ್ಥಿತಿಯನ್ನ...   
1           Positive  ಕನ್ನಡದಲ್ಲಿ ಡೈಲಿ ಟೆಕ್ ಅಪ್ಡೇಟ್ಸ್ ಪಡೆಯಲು ಸಬ್ಸ್ಕ್ರ...   
2        not-Kannada                                     Super sar song   
3           Negative  Tiktokers present situation nನೋಡುವವರು ಯಾರು ನಮ್...   
4           Positive                              Super ಸಾಂಗ್ ವೆರಿ ನೈಸ್   
...              ...                                                ...   
6207     not-Kannada  ARW tumbad tanhaji andhadhun aise bahot hai pr...   
6208     not-Kannada                   പൊളി ഡാൻസ് രക്ഷിത് ഷെട്ടി മാസ്സ്   
6209        Negative  BronNeen este Roast madudruChina ne beku antha...   
6210        Positive  ಕೌಶಲ್ಯ ಇದ್ದವರ ಸಂಖ್ಯೆ ಕಡಿಮೆ ಇಲ್ಲ ಸರ್ ತುಂಬಾ ಪ್ರತ...   
6211  Mixed feelings                                            M Views   

      Nlabel  
0          1  
1          2  
2          3  
3          1  
4          2  
...      ...  
6207       3  
6208       3  
6209       1  
6210       2  
6211       0  

[6212 rows x 3 columns]

In [46]:
Dev_Data[50:70]

category                              Msg_without_Stopwords  Nlabel
50        Negative  Guru ninge like beku andre kelu Kodthare adu b...       1
51        Positive                    super comedy drama togari tippa       2
52   unknown state                                   Deekshit Chandra       4
53        Positive  Enadru public help ago Vishayada bagge Mathadi...       2
54        Positive                      Nammantavrge spoorti nivu sir       2
55        Positive           Estu kelidru matte matte kelbeku ansutte       2
56        Positive                               Pakka days movie edu       2
57        Positive                            Nice story togari tippa       2
58        Positive       ಶಂಕರ್ ಅಶ್ವಥ್ ರೊಂದಿಗೆ ಅತ್ಯಂತ ಸುಂದರವಾದ ಸಂದರ್ಶನ       2
59     not-Kannada                                     Plz make Hindi       3
60     not-Kannada                                    Sooperb concept       3
61        Negative           Navu kuri Alla guru kaliyugada kaligallu       1
62     not-Kannada                    Ye movie hindi mein hogi k nahi       3
63        Positive       Please innodh video maadi bro ticktock bagge       2
64        Negative     Nodarappa yaro heludrala ban yak madbeku antha       1
65        Positive                          supernTogari Tippa Comody       2
66        Positive                 ಏ ಭೈ ಏನೋಪ ನೀ ಹಿಂಗ ಮೈ ತೊಳೆದು ಬಿಟ್ಟಿ       2
67        Negative  Kolthogiro kobri mitai mukadavle nanYappa devr...       1
68  Mixed feelings              Nav itara iroke karana Congress party       0
69        Positive  ಎಲ್ಲಾ ಇರೋನು ಒಂದೇ ಜೈ ಕರ್ನಾಟಕ ಮಾತೆ ಜೈ ಭುವನೇಶ್ವರಿ...       2

In [47]:
Test_Data

id                              Msg_without_Stopwords
0      Kan_1  ಈ ಹಾಡನ್ನು ಹಾಡಿದ ವಿಜಯ ಪ್ರಕಾಶ voice ಯಾರಿಗೆಲ್ಲಾ ಇ...
1      Kan_2                                         Jai D Boss
2      Kan_3                                     Signature move
3      Kan_4                                     Super song bro
4      Kan_5                         Wow Super agi helidira sir
..       ...                                                ...
763  Kan_764                                Thu thukali trailer
764  Kan_765  Siri gannadam galge haakbitallapa Thu yaro nin...
765  Kan_766  ನಾವೇನಾದರು ಸ್ವಾಬಿಮಾನಿಯಾಗಿ ಬದುಕನ್ನು ಕಟ್ಟಿಕೊಳ್ಳಲು...
766  Kan_767  ದಿಯಾ ನೀವು ಸೋಷಿಯಲ್ ಮೀಡಿಯಾ ಅಲ್ಲಿ ಕಾಣ್ತಿಲ್ಲnದಯವಿಟ...
767  Kan_768  magaluru kade kalsi avanannu navu avanige madd...

[768 rows x 2 columns]

In [48]:
X_train=Train_Data['Msg_without_Stopwords']
y_train=Train_Data['Nlabel']

X_Dev=Dev_Data['Msg_without_Stopwords']
y_Dev=Dev_Data['Nlabel']

X_test=Test_Data['Msg_without_Stopwords']

In [49]:
X_train.shape, y_train.shape, X_Dev.shape, y_Dev.shape, X_test.shape

((6212,), (6212,), (691,), (691,), (768,))

Not_offensive                           14153     0
not-malayalam                            1287     4
Offensive_Targeted_Insult_Individual      239     2
Offensive_Untargetede                     191     3
Offensive_Targeted_Insult_Group           140     1


Not_offensive                           1779      0
not-malayalam                            163      4
Offensive_Targeted_Insult_Individual      24      2
Offensive_Untargetede                     20      3
Offensive_Targeted_Insult_Group           13      1

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True , ngram_range=(4, 5))
X=tfidf.fit_transform(X_train) 
Y=y_train
tfidf

TfidfVectorizer(ngram_range=(4, 5))

In [51]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(4, 5))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', ngram_range=(4, 5))

In [52]:
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())


(42217, 137905, 42217, 137905)

In [53]:
tfidf.vocabulary_

{'ಶದ ವರ ಅದರ ಆರ': 41445,
 'ವರ ಅದರ ಆರ ಯನ': 41140,
 'ಅದರ ಆರ ಯನ ಅವಲ': 31333,
 'ಆರ ಯನ ಅವಲ ಅವರ': 32546,
 'ಯನ ಅವಲ ಅವರ ನವ': 39640,
 'ಅವಲ ಅವರ ನವ ಯತ': 32084,
 'ಅವರ ನವ ಯತ ಯಲ': 32031,
 'ನವ ಯತ ಯಲ ಎಷ': 38068,
 'ಯತ ಯಲ ಎಷ ಸಮರ': 39573,
 'ಯಲ ಎಷ ಸಮರ ಥರ': 39760,
 'ಎಷ ಸಮರ ಥರ ಎನ': 33705,
 'ಸಮರ ಥರ ಎನ ದನ': 41756,
 'ಥರ ಎನ ದನ ಅವಲ': 36601,
 'ಎನ ದನ ಅವಲ ರತದಲ': 33514,
 'ದನ ಅವಲ ರತದಲ ಅನಕ': 36674,
 'ಅವಲ ರತದಲ ಅನಕ ಷರತ': 32086,
 'ರತದಲ ಅನಕ ಷರತ ಇದ': 40239,
 'ಅನಕ ಷರತ ಇದ ಅನಕ': 31470,
 'ಷರತ ಇದ ಅನಕ ಷರಸ': 41609,
 'ಇದ ಅನಕ ಷರಸ ಥರನ': 32662,
 'ಅನಕ ಷರಸ ಥರನ ಅವರ': 31472,
 'ಷರಸ ಥರನ ಅವರ ಅನಕ': 41613,
 'ಥರನ ಅವರ ಅನಕ ಷರತ': 36609,
 'ಶದ ವರ ಅದರ ಆರ ಯನ': 41446,
 'ವರ ಅದರ ಆರ ಯನ ಅವಲ': 41141,
 'ಅದರ ಆರ ಯನ ಅವಲ ಅವರ': 31334,
 'ಆರ ಯನ ಅವಲ ಅವರ ನವ': 32547,
 'ಯನ ಅವಲ ಅವರ ನವ ಯತ': 39641,
 'ಅವಲ ಅವರ ನವ ಯತ ಯಲ': 32085,
 'ಅವರ ನವ ಯತ ಯಲ ಎಷ': 32032,
 'ನವ ಯತ ಯಲ ಎಷ ಸಮರ': 38069,
 'ಯತ ಯಲ ಎಷ ಸಮರ ಥರ': 39574,
 'ಯಲ ಎಷ ಸಮರ ಥರ ಎನ': 39761,
 'ಎಷ ಸಮರ ಥರ ಎನ ದನ': 33706,
 'ಸಮರ ಥರ ಎನ ದನ ಅವಲ': 41757,
 'ಥರ ಎನ ದನ ಅವಲ ರತದಲ': 36602,
 'ಎನ ದನ ಅವಲ ರತದಲ ಅನಕ': 33515,
 'ದನ ಅವಲ ರತದಲ ಅನಕ ಷರತ': 3667

In [54]:
char_tfidf.vocabulary_

{'ಒಂದು': 86752,
 'ಂದು ': 84523,
 'ದು ದ': 97926,
 'ು ದೇ': 124780,
 ' ದೇಶ': 9918,
 'ದೇಶದ': 98532,
 'ೇಶದ ': 130096,
 'ಶದ ಮ': 114315,
 'ದ ಮು': 96970,
 ' ಮುಂ': 11118,
 'ಮುಂದ': 104886,
 'ುಂದು': 125430,
 'ಂದುವ': 84576,
 'ದುವರ': 98098,
 'ುವರಿ': 126365,
 'ವರಿಯ': 113169,
 'ರಿಯು': 108210,
 'ಿಯುವ': 122784,
 'ಯುವು': 106399,
 'ುವುದ': 126405,
 'ವುದು': 113900,
 'ುದು ': 125895,
 'ದು ಅ': 97831,
 'ು ಅದ': 124292,
 ' ಅದರ': 7594,
 'ಅದರ ': 85058,
 'ದರ ಆ': 97222,
 'ರ ಆರ': 106739,
 ' ಆರ್': 7978,
 'ಆರ್ಥ': 85728,
 'ರ್ಥಿ': 109670,
 '್ಥಿಕ': 134191,
 'ಥಿಕ ': 96510,
 'ಿಕ ಸ': 121300,
 'ಕ ಸ್': 86986,
 ' ಸ್ಥ': 12123,
 'ಸ್ಥಿ': 116217,
 '್ಥಿತ': 134197,
 'ಥಿತಿ': 96518,
 'ಿತಿಯ': 121883,
 'ತಿಯನ': 95486,
 'ಿಯನ್': 122689,
 'ಯನ್ನ': 105859,
 'ನ್ನು': 101599,
 '್ನು ': 134728,
 'ನು ಅ': 100595,
 'ು ಅವ': 124323,
 ' ಅವಲ': 7758,
 'ಅವಲಂ': 85374,
 'ವಲಂಬ': 113285,
 'ಲಂಬಿ': 110131,
 'ಂಬಿಸ': 84802,
 'ಬಿಸು': 103250,
 'ಿಸುವ': 123344,
 'ಸುವು': 115800,
 'ವುದಿ': 113898,
 'ುದಿಲ': 125885,
 'ದಿಲ್': 97726,
 'ಿಲ್ಲ': 123088,
 'ಲ್ಲ ': 111500,
 '್ಲ ಅ':

In [55]:
X, X_char

(<6212x42217 sparse matrix of type '<class 'numpy.float64'>'
 	with 42792 stored elements in Compressed Sparse Row format>,
 <6212x137905 sparse matrix of type '<class 'numpy.float64'>'
 	with 522097 stored elements in Compressed Sparse Row format>)

In [56]:
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<6212x180122 sparse matrix of type '<class 'numpy.float64'>'
	with 564889 stored elements in COOrdinate format>

In [57]:
Xt=tfidf.transform(X_Dev) 
Xt_char=char_tfidf.transform(X_Dev)

In [58]:
Xt, Xt_char

(<691x42217 sparse matrix of type '<class 'numpy.float64'>'
 	with 88 stored elements in Compressed Sparse Row format>,
 <691x137905 sparse matrix of type '<class 'numpy.float64'>'
 	with 49130 stored elements in Compressed Sparse Row format>)

In [59]:
Dev=hstack([Xt,Xt_char])
Dev

<691x180122 sparse matrix of type '<class 'numpy.float64'>'
	with 49218 stored elements in COOrdinate format>

In [60]:
test_Mal_Hasoc_word=tfidf.transform(X_test)
test_Mal_Hasoc_char=char_tfidf.transform(X_test)
test_Mal_Hasoc_word_char=hstack([test_Mal_Hasoc_word,test_Mal_Hasoc_char])

In [61]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, f1_score

e:\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [62]:
def trainer(model_obj, param, X, X_char, train, Xt, Xt_char, Dev, Y, y_Dev):
   
    model_obj.fit(X,Y)
#Training Classifier with TF-IDF Features Word n-gram
    print("Accuracy of Word n-gram(1,2) :", (model_obj.score(Xt, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Xt)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=model_obj.predict(test_Mal_Hasoc_word)
    
    pre=precision_score(y_Dev, predict, average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

#Training Classifier with TF-IDF Features Char n-gram
    model_obj.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,5) :", (model_obj.score(Xt_char, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Xt_char)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=model_obj.predict(test_Mal_Hasoc_char)
    
    pre=precision_score(y_Dev, predict, average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)
        
              
#Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    model_obj.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (model_obj.score(Dev, y_Dev)))
#Printing Classification Report
    predict=model_obj.predict(Dev)
    print(classification_report(y_Dev, predict))
#Printing Confusion Matrix
    conf_mat=confusion_matrix(y_Dev, predict)
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=model_obj.predict(test_Mal_Hasoc_word_char)
    
    pre=precision_score(y_Dev, predict,  average='micro')
    rec=recall_score(y_Dev, predict, average='micro')
    f1s=f1_score(y_Dev, predict, average='micro')
    
    print("Precision : ", pre,)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

    
    return word, char, word_char

In [63]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
trainer(MNB,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)
#w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)
# w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,2) : 0.4645441389290883
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        52
           1       0.00      0.00      0.00       139
           2       0.46      1.00      0.63       321
           3       0.00      0.00      0.00       110
           4       0.00      0.00      0.00        69

    accuracy                           0.46       691
   macro avg       0.09      0.20      0.13       691
weighted avg       0.22      0.46      0.29       691

Confusion Matrix
[[  0   0  52   0   0]
 [  0   0 139   0   0]
 [  0   0 321   0   0]
 [  0   0 110   0   0]
 [  0   0  69   0   0]]
 
Precision :  0.4645441389290883
Recall :  0.4645441389290883
F1 Score :  0.4645441389290883
Accuracy of Char n-gram(1,5) : 0.5282199710564399
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        52
           1       0.81      0.22      0.34       139
 

e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

In [64]:
#from sklearn.tree import DecisionTreeClassifier

#DTC=DecisionTreeClassifier()
#trainer(DTC,param, X, X_char, train , Xt, Xt_char, Dev, Y, y_Dev)

In [65]:
from imblearn.over_sampling import SMOTE

In [66]:
smote = SMOTE()

In [67]:
x_smote_Word, y_smote_Word = smote.fit_resample(X, Y)
x_smote_Char, y_smote_Char = smote.fit_resample(X_char, Y)
x_smote_Comb, y_smote_Comb = smote.fit_resample(train, Y)

In [68]:
Y.value_counts()

2    2823
1    1188
3     916
4     711
0     574
Name: Nlabel, dtype: int64

In [69]:
x_smote_Word.shape, y_smote_Word.shape, x_smote_Char.shape, y_smote_Char.shape, x_smote_Comb.shape, y_smote_Comb.shape

((14115, 42217),
 (14115,),
 (14115, 137905),
 (14115,),
 (14115, 180122),
 (14115,))

In [70]:
# Development Dataset
x_smote_Word_Dev, y_smote_Word_Dev = smote.fit_resample(Xt, y_Dev)
x_smote_Char_Dev, y_smote_Char_Dev = smote.fit_resample(Xt_char, y_Dev)
x_smote_Comb_Dev, y_smote_Comb_Dev = smote.fit_resample(Dev, y_Dev)

In [71]:
x_smote_Word_Dev.shape, y_smote_Word_Dev.shape, x_smote_Char_Dev.shape, y_smote_Char_Dev.shape, x_smote_Comb_Dev.shape, y_smote_Comb_Dev.shape

((1605, 42217), (1605,), (1605, 137905), (1605,), (1605, 180122), (1605,))

In [72]:
from sklearn.model_selection import GridSearchCV


In [73]:
def trainer1111(model_obj, param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev):
    # Training Classifier  with TF-IDF Features Word n-gram(1,2)
    GSCV=GridSearchCV(model_obj, param , cv=10,return_train_score=False)
    GSCV.fit(x_smote_Word, y_smote_Word)
    print("Accuracy of Word n-gram(1,1) :", (GSCV.score(x_smote_Word_Dev, y_smote_Word_Dev)))
    #Printing Classification Report
    predict=GSCV.predict(x_smote_Word_Dev)
    print(classification_report(y_smote_Word_Dev, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Word_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Mal_Hasoc_word)
 
    accuracy = accuracy_score(y_smote_Word_Dev, predict)
    recall = recall_score(y_smote_Word_Dev, predict, average='micro')
    precision = precision_score(y_smote_Word_Dev, predict, average='micro')
    f1score = f1_score(y_smote_Word_Dev, predict, average='micro')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    
    #Training Classifier with TF-IDF Features Char n-gram(1,5)
    GSCV.fit(x_smote_Char, y_smote_Char)
    print("Accuracy of Char n-gram(1,5) :", (GSCV.score(x_smote_Char_Dev, y_smote_Char_Dev)))
    predict=GSCV.predict(x_smote_Char_Dev)
    print(classification_report(y_smote_Char_Dev, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Char_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Mal_Hasoc_char)
    
    accuracy = accuracy_score(y_smote_Char_Dev, predict)
    recall = recall_score(y_smote_Char_Dev, predict, average='micro')
    precision = precision_score(y_smote_Char_Dev, predict, average='micro')
    f1score = f1_score(y_smote_Char_Dev, predict, average='micro')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    
   
    
    
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(x_smote_Comb, y_smote_Comb)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(x_smote_Comb, y_smote_Comb)))
    #Printing Classification Report
    predict=GSCV.predict(x_smote_Comb_Dev)
    print(classification_report(y_smote_Comb_Dev, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_smote_Comb_Dev, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Mal_Hasoc_word_char)
    
    accuracy = accuracy_score(y_smote_Comb_Dev, predict)
    recall = recall_score(y_smote_Comb_Dev, predict, average='micro')
    precision = precision_score(y_smote_Comb_Dev, predict, average='micro')
    f1score = f1_score(y_smote_Comb_Dev, predict, average='micro')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))
    
    return word, char, word_char

In [74]:
from sklearn.naive_bayes import MultinomialNB
MNB11=MultinomialNB()
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
#trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)
w_mnb,c_mnb,wc_mnb=trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

Multi Nominal Bayes
Accuracy of Word n-gram(1,1) : 0.2118380062305296
              precision    recall  f1-score   support

           0       0.20      0.96      0.33       321
           1       0.38      0.02      0.05       321
           2       0.82      0.04      0.08       321
           3       1.00      0.03      0.06       321
           4       0.00      0.00      0.00       321

    accuracy                           0.21      1605
   macro avg       0.48      0.21      0.10      1605
weighted avg       0.48      0.21      0.10      1605

Best Parameters  {'alpha': 2.0}
Best Score  0.48460166277507966
 
Confusion Matrix
[[308  13   0   0   0]
 [313   8   0   0   0]
 [306   0  14   0   1]
 [311   0   0  10   0]
 [318   0   3   0   0]]
 
accuracy: 0.2118380062305296, recall: 0.2118380062305296, precision: 0.2118380062305296, f1-score: 0.21183800623052956
Accuracy of Char n-gram(1,5) : 0.5258566978193147
              precision    recall  f1-score   support

           0    

In [80]:
#c_mnb

In [ ]:
Positive   2       2823
Negative   1       1188
not-Kannada  3      916
unknown state 4     711
Mixed feelings  0   574

In [81]:
wc_mnb=pd.DataFrame(wc_mnb, columns=["Word_MNB"])
FINAL=pd.concat([X_test, wc_mnb], axis=1)
FINAL=FINAL.rename(columns={"Msg_without_Stopwords": "text", "Word_MNB": "label"})

FINAL['label'] = FINAL['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Kannada', 4 : 'unknown_state'})
FINAL[76:87]

text           label
76              Namma galli goo bandiddru ashwatthama        Negative
77          ಅವಾಗ ಕಬ್ಜ ದರ್ಶನ ಇವ್ರೆಲ್ಲಾ ಬಂದು ಕೆಡವಕ್ತಾರೆ        Negative
78                Hahahaha LoL nIdiot beggar get lost  Mixed_feelings
79  ಲಾಕ್ ಡೌನ್ ಸಮಯದಲ್ಲಿ ಕಾರ್ಮಿಕರು ವಲಸಿಗರು ರೆಸ್ತೆ ಮೇ...        Positive
80  ಮ್ಯೂಸಿಕ್ ಡೈರೆಕ್ಟರ್ ಗೆ ಒಂದು ದೊಡ್ಡ ಸಲಾಂ ಯಾವುದೋ ಲ...        Positive
81                         Fan war shuru madbeda guru        Negative
82              adeno gottilla tumba ista ayta nimage        Positive
83                            ಹೊಸ ಪ್ರಯೋಗ ಯಶಸ್ಸು ಸಿಗಲಿ        Positive
84                              ಹೌದೋ ಹುಲಿಯಾಹಾಡು ಸೂಪರ್  Mixed_feelings
85  Ŕävîñđŕå GøWđřú neenu beedhi soole maga neene ...        Negative
86                                 Gandu loafer jeena        Negative

In [82]:
FINAL.to_csv("MNB_Kannada_HASOC21.tsv")

In [138]:
from sklearn.naive_bayes import MultinomialNB
DTC1=DecisionTreeClassifier()
param={'criterion':('gini', 'entropy')}
print("Multi Nominal Bayes")
#trainer1111(MNB11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)
w_mnb,c_mnb,wc_mnb=trainer1111(DTC1,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

Multi Nominal Bayes
Accuracy of Word n-gram(1,1) : 0.41993769470404985
              precision    recall  f1-score   support

           0       0.19      0.16      0.17       321
           1       0.58      0.50      0.54       321
           2       0.37      0.61      0.46       321
           3       0.53      0.55      0.54       321
           4       0.47      0.28      0.35       321

    accuracy                           0.42      1605
   macro avg       0.43      0.42      0.41      1605
weighted avg       0.43      0.42      0.41      1605

Best Parameters  {'criterion': 'gini'}
Best Score  0.7582089732032613
 
Confusion Matrix
[[ 51  58 137  50  25]
 [ 47 162  83  18  11]
 [ 25  31 196  49  20]
 [ 40   7  55 176  43]
 [111  23  58  40  89]]
 
accuracy: 0.41993769470404985, recall: 0.41993769470404985, precision: 0.41993769470404985, f1-score: 0.41993769470404985


KeyboardInterrupt: 

# Positive          6421 2
unknown_state     5279 4
Negative          2105 1
not-malayalam     1157 3
Mixed_feelings     926 0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC11=RandomForestClassifier()
param={'n_estimators': [200, 400, 600, 800, 1000, 1200]}
print("RFC")
#param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_mnb,c_mnb,wc_mnb=trainer1111(RFC11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

RFC


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC11=RandomForestClassifier()
param={'n_estimators': [50, 100, 200, 400]}
print("RFC")
#param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_mnb,c_mnb,wc_mnb=trainer1111(RFC11,param, x_smote_Word,y_smote_Word, x_smote_Char,y_smote_Char, x_smote_Comb ,y_smote_Comb, x_smote_Word_Dev, y_smote_Word_Dev, x_smote_Char_Dev,y_smote_Char_Dev, x_smote_Comb_Dev, y_smote_Comb_Dev)

In [1]:
pip install inltk

Note: you may need to restart the kernel to use updated packages.


In [2]:
from inltk.inltk import setup
setup('hi')

In [1]:
pip install indic-nlp-library

Note: you may need to restart the kernel to use updated packages.


In [14]:
from indicnlp.transliterate.unicode_transliterate import UnicodeIndicTransliterator

# Input text "Today the weather is good. Sun is bright and there are no signs of rain. Hence we can play today."
input_text='ente mammookka ningal puliyalla oru simhama'

# Transliterate from Hindi to Telugu
print(UnicodeIndicTransliterator.transliterate(input_text,"en","ml"))

ente mammookka ningal puliyalla oru simhama


In [18]:
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator

input_text=u'आज मौसम अच्छा है। इसलिए हम आज खेल सकते हैं!'

# Transliterate Hindi to Roman
print(ItransTransliterator.to_itrans(input_text, 'ta'))

आज मौसम अच्छा है। इसलिए हम आज खेल सकते हैं!


In [20]:
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator

input_text = u'ஒன்றுமட்டுமல்லாது'
lang='ta'
input_text = ItransTransliterator.to_itrans(input_text,lang)
print(input_text)
#OUTPUT : .oऩRumaTTumallAtu

from indicnlp.transliterate.unicode_transliterate import ItransTransliterator
lang='ta'
x=ItransTransliterator.from_itrans(input_text,lang)
print(x) 
#OUTPUT :  ஒனறுமட்டுமல்லாது

ஒுமுமாு
ஒுமுமாு
