In [1]:
from sklearn.datasets import load_files
import pandas as pd

In [2]:
#Malayalam
Mal_train=pd.read_csv("tamil_sentiment_full_train.tsv", sep='\t')


Mal_Dev=pd.read_csv("tamil_sentiment_full_dev.tsv", sep='\t')


Mal_test=pd.read_csv("tamil_sentiment_full_test_withoutlabels.tsv", sep='\t')

In [3]:
Mal_train

text        category
0      Vani bhojam fans hit like solli 500 like Vangi...   unknown_state
1                           I love you ajith very I like        Positive
2      ennaya trailer Ku mudi Ellam nikkudhu... Vera ...        Positive
3               Vijay Annaa  Ur Maassssss Therrrrriiiiii        Positive
4                            நம்ப நடே நாசாமா தான் போச்சி        Negative
...                                                  ...             ...
35651  ஒருவர் செய்த தவறுக்காக எல்லாரையும் பழி போடுவது...  Mixed_feelings
35652  Repeated Mode to Watching Theri Trailer & Ther...        Positive
35653  yeevanikuachu  pula kutti erudhal oodi poyidu....        Negative
35654                 She is looking like laughing budha        Positive
35655                   NORTH OR SOUTH KGF IS THE BEST!!        Positive

[35656 rows x 2 columns]

In [4]:
Mal_train[0:5], Mal_Dev[0:5]

(                                                text       category
 0  Vani bhojam fans hit like solli 500 like Vangi...  unknown_state
 1                       I love you ajith very I like       Positive
 2  ennaya trailer Ku mudi Ellam nikkudhu... Vera ...       Positive
 3           Vijay Annaa  Ur Maassssss Therrrrriiiiii       Positive
 4                        நம்ப நடே நாசாமா தான் போச்சி       Negative,
                                                 text       category
 0  @0:40 songsuperb..kamallllla..  I'm waiting fo...  unknown_state
 1  கணத்ததோர் அகமுடையார் சார்பாக  படம் வெற்றி அடைய...       Positive
 2  Thalavia neenga veera level boss and neega tha...       Positive
 3              Oru padam patha fell.vera level music       Positive
 4  Hairstyle than mattama iruku. Adhu mattum math...  unknown_state)

In [5]:
#from ml2en import ml2en

In [6]:
#converter = ml2en()

#desti_lang={
 #    'malayalam' : 'ml'
#}

In [7]:
#for key,value in desti_lang.items():
#     #print(transt.translate(Mal_train['text']))
  #      Mal_train['text1']=Mal_train['text'].apply(lambda x: converter.transliterate(x))
    #    Mal_Dev['text1']=Mal_Dev['text'].apply(lambda x: converter.transliterate(x))
  #      Mal_test['text1']=Mal_test['text'].apply(lambda x: converter.transliterate(x))

In [8]:
Mal_train[61:70]

text        category
61       Today trailer paaka yaarellam wait panreenga   unknown_state
62  mayiru maadiri iruku thevidiya pasagala Rajini...        Negative
63  Saguni padam madhiri theriudhu,soori irukkurad...  Mixed_feelings
64  Ada paavingala mangatha theme. Aaa. Slow. Moti...        Negative
65  Kangana look like same I just love this first ...        Positive
66  wowwwwwwwwww thalaya aaaaaa masssssssss dialog...        Positive
67  3 supar dupar star akshaya rajnikant and any j...        Positive
68                  Coffee solunga marana masss thala        Positive
69                            598K left for 15M views   unknown_state

In [9]:
Mal_Dev.head()

text       category
0  @0:40 songsuperb..kamallllla..  I'm waiting fo...  unknown_state
1  கணத்ததோர் அகமுடையார் சார்பாக  படம் வெற்றி அடைய...       Positive
2  Thalavia neenga veera level boss and neega tha...       Positive
3              Oru padam patha fell.vera level music       Positive
4  Hairstyle than mattama iruku. Adhu mattum math...  unknown_state

In [10]:
Mal_test.head()

id                                               text
0  Tam_1  வீர செங்குந்தர் சார்பாக இந்த திரைப்படம் வெற்றி...
1  Tam_2  Teruk ah irukku .... mokke movie .. waste of time
2  Tam_3  manitha samuthaayam amaipil irunthu intha pada...
3  Tam_4                                   JJ mam we miss u
4  Tam_5          Subtitle me traller dekhne wale like karo

In [11]:
Mal_train=Mal_train.replace(to_replace =["Positive "], value ="Positive") 
Mal_train.shape

(35656, 2)

In [12]:
# Train
Mal_train['category'].value_counts()

Positive          20070
unknown_state      5628
Negative           4271
Mixed_feelings     4020
not-Tamil          1667
Name: category, dtype: int64

In [13]:
# Development 
Mal_Dev['category'].value_counts()

Positive          2257
unknown_state      611
Negative           480
Mixed_feelings     438
not-Tamil          176
Name: category, dtype: int64

In [14]:
msg=Mal_train['text']

msgDev=Mal_Dev['text']

msgTest=Mal_test['text']

In [15]:
msgDev[50:70]

50    Bigil=like Kaithi= cmnt Idhu epdi irruku vj fn...
51    Camne bole trending kt malaysia? Yg dri malays...
52             Auto like alludhu vekkama illayada?? Thu
53    Itha paartha kaapan maathiri illa adhavan 2 ma...
54                         333k likes thala Ajith storm
55    மோகன் அண்ணா மேன்மேலும் திரைப்படத்துறையில் வளர ...
56    01.Namba kita kaadu iruntha eduthukuvango 02.r...
57    சாதிய ஒழிக்கனுனு koovitu... சாதி வெறி புடிச்ச ...
58    I think sema line Ravi pidisu irukaaru. Sema j...
59    Like here like here nu solravanga enaku like p...
60    அடுத்தவங்க இசையை பயன்படுத்துகிறவங்க எல்லாம்......
61    My fevret Hero Akshay kumar  Supar Dupar hogi ...
62    VANNIYAR kottai dharmapuri padaiyachi Vanniyar...
63                    Pwoli  rakshit shetty kerala fans
64    Simbu zindhabad from all kannada power  puneet...
65    Avalavu nalla illai.. I'm not a superstar hate...
66                          Str da ..goyala str fans da
67           Padoo mass ah iruka podhu but tn la

In [16]:
#Remove Emojis

def emoji(msg): 
    
    msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
    
    msg_digit=msg_emoj.str.replace(r'[0-9]', ' ')

    msg_Spac = msg_digit.str.replace(r'_',' ')

    msg_Spac = msg_Spac.str.replace(r'.','')

    msg_Spac = msg_Spac.str.replace(r'!','')

    msg_Spac = msg_Spac.str.replace(r'#','')

    msg_Spac = msg_Spac.str.replace(r'%','')

    msg_Spac = msg_Spac.str.replace(r'&','')

    msg_Spac = msg_Spac.str.replace(r'’','')

    msg_Spac = msg_Spac.str.replace(r'(','')

    msg_Spac = msg_Spac.str.replace(r')','')

    msg_Spac = msg_Spac.str.replace(r'-','')

    msg_Spac = msg_Spac.str.replace(r'/','')

    msg_Spac = msg_Spac.str.replace(r':','')

    msg_Spac = msg_Spac.str.replace(r';','')

    msg_Spac = msg_Spac.str.replace(r'<','')

    msg_Spac = msg_Spac.str.replace(r'=','')

    msg_Spac = msg_Spac.str.replace(r'>','')

    msg_Spac = msg_Spac.str.replace(r'?','')

    msg_Spac = msg_Spac.str.replace(r'@','')

    msg_Spac = msg_Spac.str.replace(r'[','')

    msg_Spac = msg_Spac.str.replace(r']','')

    msg_Spac = msg_Spac.str.replace(r'^','')

    msg_Spac = msg_Spac.str.replace(r'{','')

    msg_Spac = msg_Spac.str.replace(r'}','')

    msg_Spac = msg_Spac.str.replace(r'|','')

    msg_Spac = msg_Spac.str.replace(r'~','')

    msg_Spac = msg_Spac.str.replace(r'+','')

    msg_Spac = msg_Spac.str.replace(r'\s+', ' ')


    return msg_Spac
    

In [17]:
msg_Train=emoji(msg)

msg_Dev=emoji(msgDev)

msg_Test=emoji(msgTest)

e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: The default value of regex will c

In [18]:
msg_Train[78:90], msg_Dev[50:70], #msg_Test[21:22]


(78    Cmnt section pona like here like here nu uyira...
 79                        tranding kyu ni aa rahi h yrr
 80                  Mrana Mass iliya suppr star DHANUSH
 81    vera level pakka blockbuster for sure all d be...
 82    வன்னியர் சாதி சார்பாக படம் வெற்றி பெற வாழ்த்து...
 83             Yuvan bgm vera level i love u yuvan anna
 84    Rishi Richard Fans Club சார்பாக படம் வெற்றியடை...
 85    ஜெயம் ரவி அண்ணா வாழ்த்துக்கள் நீங்க இதே மாதிரி...
 86    படம் வெற்றிகரமாக அமைய வாழ்த்துக்கள் செளராஷ்டிர...
 87                      what is this rubbish Ayoooo ayo
 88            தரமா டீஸர் அதேபோல் படமும் தரமாக இருக்கும்
 89    Maximum intha mathiri msg kudukara reality Fil...
 Name: text, dtype: object,
 50    Bigillike Kaithi cmnt Idhu epdi irruku vj fns ...
 51    Camne bole trending kt malaysia Yg dri malaysi...
 52               Auto like alludhu vekkama illayada Thu
 53    Itha paartha kaapan maathiri illa adhavan maat...
 54                            k likes thala Ajith storm
 55

In [19]:
Train_Df=pd.DataFrame(msg_Train)
Train_Df.columns=['Msg_with_Stopwords']

Dev_Df=pd.DataFrame(msg_Dev)
Dev_Df.columns=['Msg_with_Stopwords']

Test_Df=pd.DataFrame(msg_Test)
Test_Df.columns=['Msg_with_Stopwords']

In [20]:
Train_Df.shape, Dev_Df.shape, Test_Df.shape

((35656, 1), (3962, 1), (4402, 1))

In [21]:
# Removing Null Values

Train_Df['Msg_with_Stopwords']=Train_Df['Msg_with_Stopwords'].fillna("")

Dev_Df['Msg_with_Stopwords']=Dev_Df['Msg_with_Stopwords'].fillna("")

Test_Df['Msg_with_Stopwords']=Test_Df['Msg_with_Stopwords'].fillna("")


In [22]:
Mal_train.shape, Mal_Dev.shape,Train_Df.shape, Dev_Df.shape, Test_Df.shape

((35656, 2), (3962, 2), (35656, 1), (3962, 1), (4402, 1))

In [23]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Joshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [24]:
stop_words = set(stopwords.words('english'))

In [25]:
Train_Df['Msg_without_Stopwords']=Train_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Dev_Df['Msg_without_Stopwords']=Dev_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

Test_Df['Msg_without_Stopwords']=Test_Df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [26]:
Train_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_with_Stopwords'].tolist()]
Train_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Train_Df['Msg_without_Stopwords'].tolist()]

Dev_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_with_Stopwords'].tolist()]
Dev_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Dev_Df['Msg_without_Stopwords'].tolist()]

Test_Df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_with_Stopwords'].tolist()]
Test_Df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Test_Df['Msg_without_Stopwords'].tolist()]

In [27]:
Train_Data=pd.concat([Mal_train, Train_Df], axis=1)

Dev_Data=pd.concat([Mal_Dev, Dev_Df], axis=1)

Test_Data=pd.concat([Mal_test, Test_Df], axis=1)

In [28]:
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((35656, 6), (3962, 6), (4402, 6))

In [29]:
Train_Data=Train_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Dev_Data=Dev_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)

Test_Data=Test_Data.drop(['Msg_with_Stopwords','Msg_without_Stopwords_Len', 'Msg_with_Stopwords_Len', 'text'], axis=1)


In [30]:
# Dataset Train & Dev are : (1) Message_Without_Stopwords and (2) labels
# Only Test is : (1) Message_Without_Stopwords
Train_Data.shape, Dev_Data.shape, Test_Data.shape

((35656, 2), (3962, 2), (4402, 2))

In [31]:
Train_Data[78:90]

category                              Msg_without_Stopwords
78   Positive  Cmnt section pona like like nu uyira vanguvanu...
79  not-Tamil                      tranding kyu ni aa rahi h yrr
80   Positive                Mrana Mass iliya suppr star DHANUSH
81   Positive        vera level pakka blockbuster sure best anna
82   Positive  வன்னியர் சாதி சார்பாக படம் வெற்றி பெற வாழ்த்து...
83   Positive             Yuvan bgm vera level love u yuvan anna
84   Positive  Rishi Richard Fans Club சார்பாக படம் வெற்றியடை...
85   Positive  ஜெயம் ரவி அண்ணா வாழ்த்துக்கள் நீங்க இதே மாதிரி...
86   Positive  படம் வெற்றிகரமாக அமைய வாழ்த்துக்கள் செளராஷ்டிர...
87   Negative                                 rubbish Ayoooo ayo
88   Positive          தரமா டீஸர் அதேபோல் படமும் தரமாக இருக்கும்
89   Positive  Maximum intha mathiri msg kudukara reality Fil...

In [32]:
Dev_Data

category                              Msg_without_Stopwords
0      unknown_state          songsuperbkamallllla I'm waiting dis song
1           Positive  கணத்ததோர் அகமுடையார் சார்பாக படம் வெற்றி அடைய ...
2           Positive  Thalavia neenga veera level boss neega thaan m...
3           Positive               Oru padam patha fellvera level music
4      unknown_state  Hairstyle mattama iruku Adhu mattum mathirukal...
...              ...                                                ...
3957        Positive  நாடக காதல் மிகப்பெரிய தவறு இதை தான் இந்த படம் ...
3958       not-Tamil                                 So long see suriya
3959  Mixed_feelings  Super sK ettan adipoli makkalle dec waiting sK...
3960        Positive              Minimum viewa vara veppoma thala fans
3961        Positive                         Vera Vera level da version

[3962 rows x 2 columns]

In [33]:
Test_Data

id                              Msg_without_Stopwords
0        Tam_1  வீர செங்குந்தர் சார்பாக இந்த திரைப்படம் வெற்றி...
1        Tam_2             Teruk ah irukku mokke movie waste time
2        Tam_3  manitha samuthaayam amaipil irunthu intha pada...
3        Tam_4                                      JJ mam miss u
4        Tam_5             Subtitle traller dekhne wale like karo
...        ...                                                ...
4397  Tam_4398  Ithukum dislike potta kammanattti koovaingalam...
4398  Tam_4399     Suyama Sinthikiravan super Hero Seama dialogue
4399  Tam_4400               Super thalaiva Nee mass dha eppavume
4400  Tam_4401  பெண்ணை அடிமையாக்க நினைக்கும் இந்த படம் தோல்வித...
4401  Tam_4402  Semma thalaiva alu athikama akirukum enimale e...

[4402 rows x 2 columns]

In [34]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [35]:
x_train=Train_Data.Msg_without_Stopwords
x_dev=Dev_Data.Msg_without_Stopwords
x_test=Test_Data.Msg_without_Stopwords

In [36]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 


from keras.utils import to_categorical
y_train=Train_Data['Nlabel']
y_dev=Dev_Data['Nlabel']

y_train1 = to_categorical(y_train)
y_dev1 = to_categorical(y_dev)

In [37]:
y_train.shape
from keras.preprocessing.text import Tokenizer
num_labels = 5
vocab_size = 10000
batch_size = 100
num_epochs = 10

In [38]:
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(x_train)

In [39]:
X_train1 = tokenizer.texts_to_matrix(x_train)

X_dev1 = tokenizer.texts_to_matrix(x_dev)

X_test1=tokenizer.texts_to_matrix(x_test)

In [40]:
X_train1.shape, X_dev1.shape, y_train1.shape, y_dev1.shape

((35656, 10000), (3962, 10000), (35656, 5), (3962, 5))

In [41]:
type(X_train1), type(y_train1), type(X_dev1), type(y_dev1)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [42]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [43]:
#from sklearn.utils import class_weight


In [44]:
#class_weights = class_weight.compute_class_weight('balanced',np.unique(y_train),y_train)

In [158]:
#class_weights

array([1.77393035, 1.66967923, 0.35531639, 4.27786443, 1.26709311])

# Basic Mode / ANN F1 score = 0.69

In [45]:
#let us build a basic model
model = keras.Sequential([
    keras.layers.Dense(512, input_shape=(vocab_size,)),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(512),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(num_labels),
    keras.layers.Activation('softmax')
])

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               5120512   
_________________________________________________________________
activation (Activation)      (None, 512)               0         
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 2

In [46]:
num_epochs =10
batch_size = 128
history = model.fit(X_train1, y_train1, batch_size=batch_size, epochs=num_epochs,verbose=2)

Train on 35656 samples
Epoch 1/10
35656/35656 - 20s - loss: 1.0468 - accuracy: 0.6055
Epoch 2/10
35656/35656 - 17s - loss: 0.7647 - accuracy: 0.7152
Epoch 3/10
35656/35656 - 17s - loss: 0.4921 - accuracy: 0.8257
Epoch 4/10
35656/35656 - 17s - loss: 0.2696 - accuracy: 0.9083
Epoch 5/10
35656/35656 - 17s - loss: 0.1610 - accuracy: 0.9486
Epoch 6/10
35656/35656 - 17s - loss: 0.1056 - accuracy: 0.9677
Epoch 7/10
35656/35656 - 17s - loss: 0.0799 - accuracy: 0.9748
Epoch 8/10
35656/35656 - 17s - loss: 0.0648 - accuracy: 0.9799
Epoch 9/10
35656/35656 - 17s - loss: 0.0567 - accuracy: 0.9826
Epoch 10/10
35656/35656 - 17s - loss: 0.0505 - accuracy: 0.9837


In [48]:
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import precision_score, recall_score, f1_score

In [59]:
def predict(X_dev1,y_dev1,X_test1):
    loss, accuracy = model.evaluate(X_dev1,y_dev1,verbose=0)
    print('Accuracy: %f' % (accuracy*100))
    print('Loss: %f' % (loss*100))
    y_pred=model.predict_classes(X_dev1)

    # predict 
    predictions = model.predict(X_dev1, batch_size = 32)
    pred = np.argmax(predictions, axis=1)
    # label
    y_dev1 = np.argmax(y_dev1, axis=1)
    
    print(classification_report(y_dev1, pred))
    
    cohen_score = cohen_kappa_score(y_dev1, pred)
    print("Cohen Score: ",cohen_score)
    ##### PREDICTING test values ######
    y_pred=model.predict_classes(X_test1)
    df = pd.DataFrame(y_pred, columns = ['result'])
    
    precision = precision_score(y_dev1, pred, average='weighted')
    print('Precision: %f' % precision)

    recall = recall_score(y_dev1, pred, average='weighted')
    print('Recall: %f' % recall)

    f1 = f1_score(y_dev1, pred, average='weighted')
    print('F1 score: %f' % f1)
    
    return df
    

In [60]:
df=predict(X_dev1,y_dev1,X_test1)

Accuracy: 58.682483
Loss: 273.856671
              precision    recall  f1-score   support

           0       0.21      0.17      0.19       438
           1       0.39      0.36      0.38       480
           2       0.72      0.78      0.75      2257
           3       0.55      0.51      0.53       176
           4       0.41      0.36      0.38       611

    accuracy                           0.59      3962
   macro avg       0.46      0.44      0.45      3962
weighted avg       0.57      0.59      0.58      3962

Cohen Score:  0.3112951396875011
Precision: 0.567179
Recall: 0.586825
F1 score: 0.575650


In [174]:
df

result
0          2
1          1
2          2
3          2
4          1
...      ...
4397       0
4398       2
4399       2
4400       0
4401       2

[4402 rows x 1 columns]

In [175]:
FINAL=pd.concat([Test_Data.Msg_without_Stopwords, df], axis=1)
FINAL=FINAL.rename(columns={"Msg_without_Stopwords": "text", "result": "label"})

FINAL['label'] = FINAL['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Tamil', 4 : 'unknown_state'})
FINAL

text           label
0     வீர செங்குந்தர் சார்பாக இந்த திரைப்படம் வெற்றி...        Positive
1                Teruk ah irukku mokke movie waste time        Negative
2     manitha samuthaayam amaipil irunthu intha pada...        Positive
3                                         JJ mam miss u        Positive
4                Subtitle traller dekhne wale like karo        Negative
...                                                 ...             ...
4397  Ithukum dislike potta kammanattti koovaingalam...  Mixed_feelings
4398     Suyama Sinthikiravan super Hero Seama dialogue        Positive
4399               Super thalaiva Nee mass dha eppavume        Positive
4400  பெண்ணை அடிமையாக்க நினைக்கும் இந்த படம் தோல்வித...  Mixed_feelings
4401  Semma thalaiva alu athikama akirukum enimale e...        Positive

[4402 rows x 2 columns]

In [176]:
FINAL.to_csv("ANN_Tamil_HASOC21.tsv")

In [91]:
#from sklearn.metrics import confusion_matrix, classification_report
#from sklearn.metrics import cohen_kappa_score


#def emoji(y_Dev, X_Dev1, model): 
  # y_Dev1 = to_categorical(y_Dev)
 #   loss, accuracy = model.evaluate(X_Dev1,y_Dev, verbose=0)
  #  print('Accuracy: %f' % (accuracy*100))
   # print('Loss: %f' % (loss*100))
    #
    #y_pred=model.predict_classes(X_Dev1)

    
    # predict 
    #predictions = model.predict(X_Dev1, batch_size = 32)
    #pred = np.argmax(predictions, axis=1)
    # label
    #y_Dev1 = np.argmax(y_Dev, axis=1)
    
   # print(classification_report(y_Dev1, pred))
    
    #cohen_score = cohen_kappa_score(y_Dev1, pred)
    #print("Cohen Score: ",cohen_score)

In [92]:
#emoji(y_dev1, X_dev1, model)

Accuracy: 66.647792
Loss: 921.951864
              precision    recall  f1-score   support

           0       0.44      0.36      0.40       102
           1       0.60      0.52      0.56       237
           2       0.71      0.80      0.75       706
           3       0.76      0.52      0.62       141
           4       0.65      0.65      0.65       580

    accuracy                           0.67      1766
   macro avg       0.63      0.57      0.60      1766
weighted avg       0.66      0.67      0.66      1766

Cohen Score:  0.5158853789727409


In [53]:
from imblearn.over_sampling import SMOTE
smote = SMOTE('minority')


X_sm, y_sm = smote.fit_sample(X_train1, y_train1)
print(X_sm.shape, y_sm.shape)

e:\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=minority as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0 1 2 3 4] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


(54059, 10000) (54059, 5)


In [54]:
history = model.fit(X_sm, y_sm, batch_size=batch_size, epochs=num_epochs,verbose=2)

Train on 54059 samples
Epoch 1/10
54059/54059 - 63s - loss: 0.0397 - accuracy: 0.9885
Epoch 2/10
54059/54059 - 25s - loss: 0.0357 - accuracy: 0.9892
Epoch 3/10
54059/54059 - 26s - loss: 0.0351 - accuracy: 0.9896
Epoch 4/10
54059/54059 - 26s - loss: 0.0338 - accuracy: 0.9895
Epoch 5/10
54059/54059 - 25s - loss: 0.0323 - accuracy: 0.9902
Epoch 6/10
54059/54059 - 25s - loss: 0.0313 - accuracy: 0.9902
Epoch 7/10
54059/54059 - 25s - loss: 0.0278 - accuracy: 0.9912
Epoch 8/10
54059/54059 - 25s - loss: 0.0286 - accuracy: 0.9911
Epoch 9/10
54059/54059 - 26s - loss: 0.0308 - accuracy: 0.9903
Epoch 10/10
54059/54059 - 25s - loss: 0.0283 - accuracy: 0.9909


In [55]:
X_Dev_sm, y_Dev_sm = smote.fit_sample(X_dev1, y_dev1)
print(X_Dev_sm.shape, y_Dev_sm.shape)

e:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0 1 2 3 4] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


(6043, 10000) (6043, 5)


In [56]:
df_smote=predict(X_Dev_sm,y_Dev_sm,X_test1)

Accuracy: 65.050471
Loss: 280.484506
              precision    recall  f1-score   support

           0       0.22      0.18      0.20       438
           1       0.40      0.34      0.37       480
           2       0.62      0.78      0.69      2257
           3       0.96      0.75      0.84      2257
           4       0.35      0.39      0.37       611

    accuracy                           0.65      6043
   macro avg       0.51      0.49      0.49      6043
weighted avg       0.67      0.65      0.65      6043

Cohen Score:  0.4969482017087453


In [75]:
df_smote

result
0          2
1          1
2          2
3          2
4          0
...      ...
4397       1
4398       2
4399       2
4400       0
4401       2

[4402 rows x 1 columns]

In [170]:
FINAL=pd.concat([Test_Data.Msg_without_Stopwords, df_smote], axis=1)
FINAL=FINAL.rename(columns={"Msg_without_Stopwords": "text", "result": "label"})

FINAL['label'] = FINAL['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Tamil', 4 : 'unknown_state'})
FINAL

NameError: name 'df_smote' is not defined

In [ ]:
FINAL.to_csv("ANN_Malayalam_HASOC21.tsv")

#  https://shrikar.com/deep-learning-with-keras-and-python-for-multiclass-classification/

# CNN F1 score = 0.70


In [61]:
from keras.preprocessing.text import Tokenizer

In [62]:
word_tokenizer= Tokenizer()

# Train, Dev, Test
word_tokenizer.fit_on_texts(Train_Data.Msg_without_Stopwords)


In [63]:
max_length = max([len(s.split()) for s in Train_Data.Msg_without_Stopwords])
max_length

124

In [64]:
# define vocabulary size

vocab_size = len(word_tokenizer.word_index) + 1
vocab_size

69675

In [65]:
# Embeded Sentences of Train
Train_Sent = word_tokenizer.texts_to_sequences(Train_Data.Msg_without_Stopwords)

# Embeded Sentences of Dev
Dev_Sent = word_tokenizer.texts_to_sequences(Dev_Data.Msg_without_Stopwords)

# Embeded Sentences of Test
Test_Sent = word_tokenizer.texts_to_sequences(Test_Data.Msg_without_Stopwords)

In [66]:
from keras.preprocessing.sequence import pad_sequences


In [67]:
# X_train
Train_padded_sentences = pad_sequences(Train_Sent, max_length, padding='post')

# Dev
Dev_padded_sentences = pad_sequences(Dev_Sent, max_length, padding='post')

# Test
Test_padded_sentences = pad_sequences(Test_Sent, max_length, padding='post')

In [68]:
Train_Sent[0],Train_padded_sentences[0]

([1244, 20445, 12, 29, 1, 477, 1, 20446, 2032],
 array([ 1244, 20445,    12,    29,     1,   477,     1, 20446,  2032,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [69]:
model_CNN = keras.Sequential([
    keras.layers.Embedding(vocab_size, 100, input_length=max_length),
   # keras.layers.GlobalAveragePooling1D(),
    # convolutional filters=128,  kernel size=3: it means length_long_sentence size of 65 we are luking for 3 words at a time
    keras.layers.Conv1D(64, 3, activation='relu'),
    keras.layers.GlobalMaxPooling1D(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(5, activation='softmax')
])



model_CNN.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_CNN.summary()



#model = Sequential()
#model.add(Embedding(vocab_size, 100, input_length=max_length))
#model.add(Conv1D(filters=32, kernel_size=8, activation='relu'))
#model.add(MaxPooling1D(pool_size=2))
#model.add(Flatten())
#model.add(Dense(10, activation='relu'))
#model.add(Dense(1, activation='sigmoid'))


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 124, 100)          6967500   
_________________________________________________________________
conv1d (Conv1D)              (None, 122, 64)           19264     
_________________________________________________________________
global_max_pooling1d (Global (None, 64)                0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 325       
Total params: 6,987,089
Trainable params: 6,987,089
Non-trainable params: 0
_________________________________________________________________


In [70]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Train_Data['Nlabel']=le.fit_transform(Train_Data['category']) 
Dev_Data['Nlabel']=le.fit_transform(Dev_Data['category']) 

In [71]:
from keras.utils import to_categorical
y_train=Train_Data['Nlabel']
y_dev=Dev_Data['Nlabel']

y_train1 = to_categorical(y_train)
y_dev1 = to_categorical(y_dev)

In [72]:
Train_padded_sentences.shape, y_train1.shape, Dev_padded_sentences.shape, y_dev1.shape, Test_padded_sentences.shape

((35656, 124), (35656, 5), (3962, 124), (3962, 5), (4402, 124))

In [73]:
type(y_train1), type(Train_padded_sentences), type(Dev_padded_sentences), type(y_dev1), type(Test_padded_sentences)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [74]:
Train_padded_sentences=np.array(Train_padded_sentences)
y_train1=np.array(y_train1)

Train_padded_sentences.shape, y_train1.shape

((35656, 124), (35656, 5))

In [75]:
num_epochs =5
batch_size = 128
history = model_CNN.fit(Train_padded_sentences, y_train1, batch_size=batch_size, epochs=num_epochs, verbose=2)

Train on 35656 samples
Epoch 1/5
35656/35656 - 46s - loss: 1.1830 - accuracy: 0.5661
Epoch 2/5
35656/35656 - 43s - loss: 0.9058 - accuracy: 0.6714
Epoch 3/5
35656/35656 - 43s - loss: 0.6398 - accuracy: 0.7849
Epoch 4/5
35656/35656 - 43s - loss: 0.4142 - accuracy: 0.8699
Epoch 5/5
35656/35656 - 42s - loss: 0.2852 - accuracy: 0.9116


In [76]:
Dev_padded_sentences=np.array(Dev_padded_sentences)
y_dev1=np.array(y_dev1)

In [77]:
def predict_CNN(X_dev1,y_dev1,X_test1):
    loss, accuracy = model_CNN.evaluate(X_dev1,y_dev1,verbose=0)
    print('Accuracy: %f' % (accuracy*100))
    print('Loss: %f' % (loss*100))
    y_pred=model_CNN.predict_classes(X_dev1)

    # predict 
    predictions = model_CNN.predict(X_dev1, batch_size = 32)
    pred = np.argmax(predictions, axis=1)
    # label
    y_dev1 = np.argmax(y_dev1, axis=1)
    
    print(classification_report(y_dev1, pred))
    
    cohen_score = cohen_kappa_score(y_dev1, pred)
    print("Cohen Score: ",cohen_score)
    ##### PREDICTING test values ######
    y_pred=model_CNN.predict_classes(X_test1)
    df = pd.DataFrame(y_pred, columns = ['result'])
    
    precision = precision_score(y_dev1, pred, average='weighted')
    print('Precision: %f' % precision)

    recall = recall_score(y_dev1, pred, average='weighted')
    print('Recall: %f' % recall)

    f1 = f1_score(y_dev1, pred, average='weighted')
    print('F1 score: %f' % f1)
    
    return df

In [78]:
df_CNN=predict_CNN(Dev_padded_sentences,y_dev1,Test_padded_sentences)

Accuracy: 59.616357
Loss: 138.901585
              precision    recall  f1-score   support

           0       0.22      0.13      0.16       438
           1       0.44      0.32      0.37       480
           2       0.70      0.82      0.75      2257
           3       0.67      0.53      0.59       176
           4       0.38      0.35      0.37       611

    accuracy                           0.60      3962
   macro avg       0.48      0.43      0.45      3962
weighted avg       0.56      0.60      0.57      3962

Cohen Score:  0.30159385598259814
Precision: 0.562826
Recall: 0.596164
F1 score: 0.574063


In [199]:
FINAL_CNN=pd.concat([Test_Data.Msg_without_Stopwords, df_CNN], axis=1)
FINAL_CNN=FINAL_CNN.rename(columns={"Msg_without_Stopwords": "text", "result": "label"})

FINAL_CNN['label'] = FINAL_CNN['label'].map({0 : 'Mixed_feelings', 1 : 'Negative', 2: 'Positive', 3 :'not-Tamil', 4 : 'unknown_state'})
FINAL_CNN

text      label
0     வீர செங்குந்தர் சார்பாக இந்த திரைப்படம் வெற்றி...   Positive
1                Teruk ah irukku mokke movie waste time   Negative
2     manitha samuthaayam amaipil irunthu intha pada...   Positive
3                                         JJ mam miss u   Positive
4                Subtitle traller dekhne wale like karo  not-Tamil
...                                                 ...        ...
4397  Ithukum dislike potta kammanattti koovaingalam...   Negative
4398     Suyama Sinthikiravan super Hero Seama dialogue   Positive
4399               Super thalaiva Nee mass dha eppavume   Positive
4400  பெண்ணை அடிமையாக்க நினைக்கும் இந்த படம் தோல்வித...   Positive
4401  Semma thalaiva alu athikama akirukum enimale e...   Positive

[4402 rows x 2 columns]

In [226]:
FINAL_CNN.to_csv("CNN_Tamil_HASOC21.tsv")

In [310]:
#emoji(y_dev1, Dev_padded_sentences, model_CNN)

In [84]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, GRU
from keras.layers.embeddings import Embedding

In [122]:
# step 1
embedding_matrix = np.zeros((vocab_size, 300)) #create an array of zeros with word_num rows and embedding_dim columns

# step 2 & step 3
for word, index in word_tokenizer.word_index.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        embedding_matrix[index] = embedding_vector


NameError: name 'embeddings_dictionary' is not defined

In [85]:
lstm_node=32
nclasses=5

In [86]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dropout, Dense, Embedding, LSTM, Bidirectional

In [144]:
model_BiLSTM=keras.Sequential([
     # add Embeddign layer
keras.layers.Embedding(vocab_size,300, input_length=max_length, trainable=True),
    # add birectional 
keras.layers.Bidirectional(LSTM(lstm_node, return_sequences=True, recurrent_dropout=0.2)),
    # add dropout layer after  each lstm
keras.layers.Dropout(0.2),
        # add birectional 
keras.layers.Bidirectional(LSTM(lstm_node, recurrent_dropout=0.2)),
     # add dropout layer after  each lstm
keras.layers.Dropout(0.2),
    # Add the fully connected layer with 256 nurons and relu activation
keras.layers.Dense(256,activation='relu'),
    # Add the output layer with softmax activation since we have 2 classes
keras.layers.Dense(nclasses, activation='softmax')
])

model_BiLSTM.compile(loss='sparse_categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])
model_BiLSTM.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 195, 300)          12069000  
_________________________________________________________________
bidirectional_6 (Bidirection (None, 195, 64)           85248     
_________________________________________________________________
dropout_9 (Dropout)          (None, 195, 64)           0         
_________________________________________________________________
bidirectional_7 (Bidirection (None, 64)                24832     
_________________________________________________________________
dropout_10 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 256)               16640     
_________________________________________________________________
dense_11 (Dense)             (None, 5)                

In [145]:
Train_padded_sentences, Train_padded_sentences.shape

(array([[  398,   399,     9, ...,     0,     0,     0],
        [  179,  3473,  3474, ...,     0,     0,     0],
        [  194,   253,   813, ...,     0,     0,     0],
        ...,
        [ 1871,   696,   787, ...,     0,     0,     0],
        [11438,   453,  1582, ...,     0,     0,     0],
        [  543,  2190,    25, ...,     0,     0,     0]]), (15888, 195))

In [146]:
y_train1, y_train1.shape

(array([[0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.]]), (15888, 5))

In [147]:
Train_padded_sentences.shape, y_train1.shape

((15888, 195), (15888, 5))

In [164]:
Train_padded_sentences.shape, Train_Data['Nlabel'].shape, type(Train_padded_sentences), type(Train_Data['Nlabel'])

((15888, 195), (15888,), numpy.ndarray, pandas.core.series.Series)

In [168]:
train_y=Train_Data['Nlabel'].to_numpy()
type(train_y), type(y_train1)

(numpy.ndarray, numpy.ndarray)

In [170]:
history = model_BiLSTM.fit(Train_padded_sentences, y_train1, batch_size=batch_size, epochs=num_epochs, verbose=2)

Train on 15888 samples
Epoch 1/10


TypeError: 'NoneType' object is not callable

# One Hot : Bilstem

In [201]:
from tensorflow.keras.preprocessing.text import one_hot

# train

In [202]:
onehot_repr=[one_hot(words,vocab_size)for words in Train_Data.Msg_without_Stopwords] 
onehot_repr

[[914, 16033, 62443, 62344, 26008, 54005, 26008, 34466, 33183],
 [44374, 975, 62756, 44374, 26008],
 [12370, 53381, 42754, 19707, 15398, 63009, 65414, 52411, 53381],
 [61898, 45132, 18421, 30069, 8253],
 [33355, 65733, 48318, 11639, 27137],
 [48512, 65414, 52411, 30723, 5128, 34316],
 [32926, 46168, 47771, 26008, 19595, 26008, 67979],
 [57500, 52426, 57500, 12692, 23742, 61898, 69254, 65657, 69254],
 [6200, 19816, 1614, 28068, 15062, 27994, 28555],
 [948, 53105, 16396, 46422, 21770],
 [61898, 32334, 32334, 28132, 45285],
 [4954, 10159, 25508, 669, 26008, 20784],
 [16388, 44264, 29335, 49184, 67076],
 [10897, 10566, 49030, 60691, 8621, 19008, 33898, 13487, 8621],
 [5696,
  10897,
  5696,
  10897,
  63943,
  15562,
  27508,
  9436,
  13208,
  37829,
  35268,
  39210,
  44727,
  62554,
  67883,
  10955,
  32627,
  46380,
  52415,
  50348,
  19386,
  26226,
  36653,
  37829,
  22011,
  35405,
  47929,
  40951,
  33310,
  50348,
  39054,
  26226,
  26715,
  43857,
  14565],
 [30462, 8667, 2

In [203]:
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=195)
print(embedded_docs)

[[  914 16033 62443 ...     0     0     0]
 [44374   975 62756 ...     0     0     0]
 [12370 53381 42754 ...     0     0     0]
 ...
 [44208 38479 64864 ...     0     0     0]
 [68625 68030 26008 ...     0     0     0]
 [67213 17890 47931 ...     0     0     0]]


In [204]:
embedded_docs.shape, y_train1.shape

((35656, 195), (35656, 5))

# Dev

In [205]:
onehot_repr1=[one_hot(words,vocab_size)for words in Dev_Data.Msg_without_Stopwords] 
len(onehot_repr1)

3962

In [206]:
embedded_docs_dev=pad_sequences(onehot_repr1,padding='post',maxlen=195)
len(embedded_docs_dev)

3962

In [207]:
y_dev1

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [208]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y_train1)

x_dev_final=np.array(embedded_docs_dev)
y_dev_final=np.array(y_dev1)

In [209]:
len(x_dev_final)

3962

In [210]:
X_final.shape, y_final.shape, x_dev_final.shape, y_dev_final.shape

((35656, 195), (35656, 5), (3962, 195), (3962, 5))

In [211]:
from tensorflow.python.keras.layers import Dropout, Dense, Embedding, LSTM, Bidirectional
model_CNN1 = keras.Sequential([
    keras.layers.Embedding(vocab_size, 50, input_length=max_length),
   # keras.layers.GlobalAveragePooling1D(),
    # convolutional filters=128,  kernel size=3: it means length_long_sentence size of 65 we are luking for 3 words at a time
    keras.layers.Conv1D(756, 7, activation='relu'),
    keras.layers.Conv1D(756, 7, activation='relu'),
    keras.layers.MaxPool1D(),
    keras.layers.Conv1D(256, 3, activation='relu'),
    keras.layers.Conv1D(256, 3, activation='relu'),
    keras.layers.MaxPool1D(),
    keras.layers.Bidirectional(LSTM(400)),
    keras.layers.Dense(5, activation='softmax')
])

model_CNN1.compile(loss='sparse_categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])
model_CNN1.summary()

NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array.

In [ ]:
model_CNN1.fit(X_final,y_final,epochs=10,batch_size=64)

In [113]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(vocab_size,embedding_vector_features,input_length=195))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(5,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 195, 40)           1609200   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_6 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 1005      
Total params: 1,723,005
Trainable params: 1,723,005
Non-trainable params: 0
_________________________________________________________________
None


In [114]:
model1.fit(X_final,y_final,epochs=10,batch_size=64)

Train on 15888 samples
Epoch 1/10
15888/15888 [==============================] - 2813s 177ms/sample - loss: 0.4279 - accuracy: 0.8112
Epoch 2/10
15888/15888 [==============================] - 1174s 74ms/sample - loss: 0.2807 - accuracy: 0.8847
Epoch 3/10
15888/15888 [==============================] - 1182s 74ms/sample - loss: 0.1715 - accuracy: 0.9341
Epoch 4/10
15888/15888 [==============================] - 2292s 144ms/sample - loss: 0.1099 - accuracy: 0.9619
Epoch 5/10
15888/15888 [==============================] - 1207s 76ms/sample - loss: 0.0656 - accuracy: 0.9788
Epoch 6/10
15888/15888 [==============================] - 1194s 75ms/sample - loss: 0.0479 - accuracy: 0.9850
Epoch 7/10
15888/15888 [==============================] - 1190s 75ms/sample - loss: 0.0377 - accuracy: 0.9888
Epoch 8/10
15888/15888 [==============================] - 812s 51ms/sample - loss: 0.0311 - accuracy: 0.9900
Epoch 9/10
15888/15888 [==============================] - 803s 51ms/sample - loss: 0.0261 - accu

In [139]:
emoji(y_dev_final, x_dev_final, model1)

Accuracy: 86.557204
Loss: 55.181224
              precision    recall  f1-score   support

           0       0.34      0.37      0.35       102
           1       0.64      0.43      0.51       237
           2       0.69      0.74      0.71       706
           3       0.71      0.68      0.69       141
           4       0.65      0.67      0.66       580

    accuracy                           0.65      1766
   macro avg       0.60      0.58      0.59      1766
weighted avg       0.65      0.65      0.65      1766

Cohen Score:  0.495450229923202


In [104]:
Train_padded_sentences.shape, y_train1.shape, y_dev1.shape, Dev_padded_sentences.shape

((15888, 195), (15888, 5), (1766, 5), (1766, 195))